### ISSUE TITLE
Ortsauswahl über Karte und anderes Format

### ISSUE THREAD

**Issue by ThomGr** [mirsch/lab2gpx#1]
Das Tool ist sehr gut, aber die Ortsauswahl etwas unhandlich

Optimal wäre eine kleine Openstreetmap-Karte, in der man den Ort auswählen kann. Alternativ oder zusätzlich würde es helfen, wenn man die Koordinaten im typischen Geocaching Format eingeben könnte, statt Dezimal-Grad zu verwenden.

**Comment by mirsch** [comment]
beides jetzt möglich
