### ISSUE TITLE
neue Funktion: Found GPX für LAB Caches

### ISSUE THREAD

**Issue by bcas008** [mirsch/lab2gpx#101]
Da es wohl nicht möglich ist  eine "found" GPX (für absolvierte LAB Caches)  zu bekommen, wäre es prima wenn man bei lab2gps diese Funktion integrieren könnte. Aktuell stimmt meine found Datenbank in GSAK nicht mit Groundspeak überein.

Am besten wäre eine seperate Abfrage über ALLE bereits gefunden LAB Caches unabhängig von der Menge, Entfernung und vom Land.

Ich würde mich (und bestimmt andere auch) sehr freuen wenn das umgesetzt werden könnte.
Über eine Rückmeldung freut sich Manfred (aka bcas008)

**Comment by retep-55** [comment]
¡hola!
das wäre in der Tat eine gute Idee. Ich behelfe mich damit, die absolvierten ALCs händisch mit dem Funddatum zu versehen und anschliessend in meine Fund Datenbank in GSAK zu verschieben. Das Verhalten von Groundspeak kann ich auch nicht nachvollziehen.
saludos
Peter

**Comment by mirsch** [comment]
mit v4 gibt es jetzt zumindest die Möglichkeit nach absolvierten zu suchen.
Leider ist das Funddatum nicht enthalten und es gibt immer noch die Einschränkung, dass Koordinaten und Radius angegeben werden müssen
