### ISSUE TITLE
Adventure Labs along a route

### ISSUE THREAD

**Issue by tabbywmn** [mirsch/lab2gpx#106]
Would it be possible to select/draw a rectangle instead of a distance radius to download Adventure Labs?  In GSAK this is called a Bounding Box (rectangle) that one can draw across an area on a map.   This would be helpful for downloading Adventure Labs along a route.

I have tried to do this in Cachly (iPhone) where I can successfully download regular caches within the map (screen) boundaries, however, the Adventure Labs go far beyond this boundary. 

Thank you.

**Comment by mirsch** [comment]
labs api does not support this
