### ISSUE TITLE
2 labs with the same code

### ISSUE THREAD

**Issue by anvanlaer** [mirsch/lab2gpx#108]
Today i noticed something strange.  
I've done a lab art on thursday with 375 founds, and again today with 525 founds.  After i put both them arts in my found database, there were only 895 added. 
After some investigations, i saw that 2 labs series (one logged on thursday and one logged today) had the same code. So when i moved them together, only one series remained.

These are the 2 labs
https://labs.geocaching.com/goto/986c07b2-f128-48ab-9d86-98e662dc1ae4
https://labs.geocaching.com/goto/9a8ef11c-e531-448d-a443-65c2ae3d369d
And they both got the code LCDV3501 etc

**Comment by SamHenkel** [comment]
Actually the codes are NOT ident.
One is DV35 nad the other is Dv35. Note the case sensitivity.

**Comment by SamHenkel** [comment]
> I understand, yet GSAK treats them as the same.

No, GSAK does handle that quite right. YOU have to check the box "Code **nicht** in Großbuchstaben konvertieren"

**Comment by anvanlaer** [comment]
Ok, that i didn't know.  Where i can find that checkbox?

**Comment by anvanlaer** [comment]
ah i found it.  I remember for next time.  Thanks for helping me
