### ISSUE TITLE
Filter by name

### ISSUE THREAD

**Issue by NeanderGollum** [mirsch/lab2gpx#111]
Hello,
just a big THANK you for that great tool!

Currently I try to get ALCs with "Jakobsweg:" as a part of the name for complete Germany and I am wondering if there is an easier way, to get those instead of my current way: Loading ALL ALC of Germany (with roundabout 100 requests) into a GSAK database and filter there the name.

So it would be great if a filtering by name would be possible BEFORE loading all of them.

(Please ignore this post, if this issue has been already requested for, but I haven't found it).

Thanks and best regards

Andreas

**Comment by SamHenkel** [comment]
Use this GSAK macro:
[GetAdventureLabsByName.gsk](https://gsak.net/board/index.php?showtopic=36298&st=0&#entry278999)

**Comment by mirsch** [comment]
gc api does not offer a filter by name
