### ISSUE TITLE
Too many finds

### ISSUE THREAD

**Issue by monsterbox3007** [mirsch/lab2gpx#117]
Hi!

Sourcecode of my finds is more than 64k lines and this seems to be the actual limit. Any chance this could be increased? Otherwise I can't really use this tool any longer :-(

Thanks,
Christian

**Comment by monsterbox3007** [comment]
Hi!

As nothing has changed I tried to find at least a workaround by creating a filter to stay with just the needed lines of the source code. First save the source code as "source.txt" and then run a Windows command vs. it (in a command shell in the directory you saved the file).

findstr /r "data-adv-id= cache-title" source.txt > lab2gpx.txt

You will find the single lab stages in the new file and can just paste that content into the lab2gpx form. Can't tell if it's running perfect for everybody, but it seems to do the trick at least for me. As 2 lines per stage seem to be needed, it then would allow 32K finds instead of ~6K finds upfront.

Bye,
Christian

**Comment by mirsch** [comment]
new version using api v4 is online. no need for copy & paste anymore.
