### ISSUE TITLE
lab2gpx funktioniert bei mir nicht mehr

### ISSUE THREAD

**Issue by LongrunnerTom** [mirsch/lab2gpx#119]
ich bekomme nur die Antwort:

Diese Seite funktioniert nicht
gcutils.de kann diese Anfrage momentan nicht verarbeiten.
HTTP ERROR 500

**Comment by steve8x8** [comment]
Does the problem persist? Even the error message contains the word "momentan" so it may have been temporary - I've successfully queried gcutils.de just a minute ago
