### ISSUE TITLE
Kürzel wählbar

### ISSUE THREAD

**Issue by D-Buddi** [mirsch/lab2gpx#12]
Wäre schön wenn man das Code-Kürzel wählen kann. Bisher nutze ich ein Makro von GSAK und das macht vor die Lab-Caches ein "LB". Dieses (übrigens sehr coole) Tool macht ein "LC" davor. Wäre also schon wenn ich diesen ersten Teil frei wählen könnte.

MfG Jörg

**Comment by mirsch** [comment]
ist im aktuellen Release möglich
