### ISSUE TITLE
Deaktivierte Labs von Events

### ISSUE THREAD

**Issue by Mani1ac** [mirsch/lab2gpx#120]
Hallo,
ich habe versucht meine Funde zu importieren aber alte LabAdventures von Megaevents werden nicht aufgeführt. Wie bekomme  ich die in meine Statistik?

Gretes

Mani.ac

**Comment by PlasmaWave** [comment]
All completed Lab stages are shown in your geocaching.com profile. I copied my list into Excel, then extracted Lab names, completeion dates, co-ords, etc, to a text file then imported that into GSAK. Not super quick, but is a one-off task to have all your completed Lab stages in one place.

**Comment by mirsch** [comment]
duplicate of #15
