### ISSUE TITLE
Found dates

### ISSUE THREAD

**Issue by browiw** [mirsch/lab2gpx#121]
I know this has been asked before but would it be possible to mark the labs found with the date they were found. This was possible before via the Geocache site but has been removed. Would be great is this were possible.

**Comment by steve8x8** [comment]
https://labs.geocaching.com/logs has the details you need, but requires logging in - would you trust this tool to use your credentials? (You may export the HTML though - not sure whether lab2gpx could, or would, extract the date(s) from there. As far as I can see there's no indication of whether the ALC has been completed - so be careful with incomplete ones.)

Also, there's a found date per waypoint - and a log date for the whole ALC which not necessarily coincides with the find date for the last WP...

**Comment by mirsch** [comment]
unfortunately found date is not included in the api response

**Comment by wernerschka** [comment]
I think there might be 2 options to receive found dates: 

1) Within the latest Lab-app, there's an entry _"Profile > Postcard collection"_ where we can see dates on the postcards. So there is an API-function delivering found dates.

2) On the Website https://labs.geocaching.com/logs_ completed dates are delivered too, by calling an API-function which delivers the finds of a certain player by .json file.
