### ISSUE TITLE
Wishlist item: Zone size (radius)

### ISSUE THREAD

**Issue by steve8x8** [mirsch/lab2gpx#122]
In my home zone, there are a few ALCs that have extraordinarily large "zones" (the circles you have to enter to unlock the question), and a few others where it becomes difficult to find the right place to go.
From previous own attempts I know that the zone size is available per ALC waypoint. Would it be possible to provide this information either with the waypoint name or description?

**Comment by steve8x8** [comment]
BTW this seems to be a duplicate of #110 ...

**Comment by mirsch** [comment]
duplicate of #110
