### ISSUE TITLE
Super, die App GCDroid kann die GPX auch importieren 

### ISSUE THREAD

**Issue by glider74** [mirsch/lab2gpx#13]
Danke! Sogar mit lab Icon Anzeige in der App

Natürlich wünscht man sich immer eine Integration mit Apps ohne Medienbrüche... aber das ist so schon mal super.

Ich bestätige also auch, daß es mit der App GCDroid funktioniert. Nimm gerne den Hinweis auf, getestet auf Android (11) GCDroid. 
![Screenshot_20210206-163737_GCDroid](https://user-images.githubusercontent.com/985950/107122789-187c8c80-689a-11eb-9983-8ee056797688.jpg)

**Comment by glider74** [comment]
![Uploading Screenshot_20210206-163737_GCDroid.jpg…]()

**Comment by glider74** [comment]
![Uploading Screenshot_20210206-163737_GCDroid.jpg…]()

**Comment by mirsch** [comment]
Danke für den Hinweis, schön das es funktioniert
