### ISSUE TITLE
lab2gpx not picking up any ALs

### ISSUE THREAD

**Issue by lynnd1711** [mirsch/lab2gpx#131]
I have tried several times today to download several ALs in one area but get none. There are 20 individual ALs minimum in this area.

**Comment by lynnd1711** [comment]
Hi Harald,

I can now download ALs except for the area that I tried to download when the server was down. Could something have become corrupted? The area I centred on was 51.17222, -1.77026, radius 10km.

Thank you

**Comment by SamHenkel** [comment]
Use a 20 kms range as there are no LabCaches within 10 kms from your centre point. ;-)

**Comment by lynnd1711** [comment]
Yes there are, four sets. Stonehenge, Historic Amesbury, Historic Amesbury 2 and HA 3. It's s as if kab2gpx no longer sees them. If I increase the radius it picks up others but not these that I am interested in. 
![Screenshot_20231027-062647_Adventure Lab](https://github.com/mirsch/lab2gpx/assets/149073496/952123f0-e203-46c9-aafd-e0f2b306ddf9)

**Comment by mirsch** [comment]
should be fixed since v4 api
