### ISSUE TITLE
excluding Labs via UUID list does not work

### ISSUE THREAD

**Issue by UlliH1** [mirsch/lab2gpx#132]
Example:
Coordinates = N 48° 21.955 E 10° 53.667 (Augsburg Königsplatz)
I would like to exclude the two Lab series
Augsburger Plätze
MEMORY 

In the "UUIDs ausschließen" field I inserted:
LCRW42
LCS7UJ

(= IDs of these two Lab series)
However, in the downloaded labs2gpx.gpx these are still included (at first positions)
Am I just using a wrong format?
Or why doesn't it work at all?

**Comment by SamHenkel** [comment]
You're using the Waypoint codes. Use guids instead. That is:
6cfcadfc-98bc-4035-8ae3-7d60c0b8e5ed
7e2a8104-6407-48ff-9b0d-01e42f6b256b

**Comment by UlliH1** [comment]
Oh, this was already helpful. But where do I get this guid from? 
I couldn't find it in the gpx file.
