### ISSUE TITLE
excluding already logged labs doesnt work 

### ISSUE THREAD

**Issue by GuidoB2024** [mirsch/lab2gpx#136]
Hi ! 
I try to exclude the founds by copying (of course after proper login on that page)
view-source:https://labs.geocaching.com/logs 

into field "exclude founds" ("Deine Funde ausschließen, Source Code der Seite Deiner Funde kopieren & einfügen:")
However, they are still included in the generated list.
Doesnt matter if I use Safari on Mac or Chrome in Windows PC :-(

Do you have a hint for me?

thanks tons
Guido

**Comment by mirsch** [comment]
new version using api v4 is online. no need for copy & paste anymore.
