### ISSUE TITLE
System arbeitet nicht

### ISSUE THREAD

**Issue by mawe999** [mirsch/lab2gpx#137]
Es werden keine Lösungen gezeigt. außer keine Ergebnisse für deine Suche

**Comment by SamHenkel** [comment]
Der AdventureLab-Server scheint momentan down zu sein. Deshalb gibt es wohl auch keine Ergebnisse.

**Comment by mawe999** [comment]
Hallo,
vielen Dank für die Info. 
Das ist übrigens ein SUPER System! 
Grüße Werner
