### ISSUE TITLE
wording / Award / Tagebucheinträge

### ISSUE THREAD

**Issue by glider74** [mirsch/lab2gpx#14]
Es kann der Eindruck entstehen, dass Lösungen bekannt gegeben werden. Es sind aber die Tagebucheinträge gemeint. Wenn dort doch den Owner keine Hinweise eingegeben werden, gibt's auch keine Lösungen.
Vielleicht sollte das wording in der Beschreibung dahingehend geschärft werden.

Award können einige Vielleicht nicht einordnen. 
Die App nutzt die Begriffe Tagebucheinträge bzw. Journal.

![Screenshot_20210206-190901_Firefox Beta](https://user-images.githubusercontent.com/985950/107126230-db6ec500-68ae-11eb-9769-9e8159bfb60b.jpg)

![Screenshot_20210206-192919_Adventure Lab](https://user-images.githubusercontent.com/985950/107126717-afa10e80-68b1-11eb-9439-310f89e08584.jpg)
![Screenshot_20210206-192604_Adventure Lab](https://user-images.githubusercontent.com/985950/107126720-b3349580-68b1-11eb-8614-bf51333ca16a.jpg)

**Comment by mirsch** [comment]
ich habe das angepasst und hoffe es ist nun eindeutiger
