### ISSUE TITLE
All points of a partially solved ALC are included in the GPX

### ISSUE THREAD

**Issue by hmpfgnrrr** [mirsch/lab2gpx#140]
Current behavior:
With API v4 when you download with option "Teilweise abgeschlossene Labs einschließen" an ALC that was only solved partially then all lab points are included in the GPX file.

Requested behavior:
Only the lab points that are not yet completed shall be included in the GPX. Like it was with API v3.

**Comment by mirsch** [comment]
should be fixed now.
Partially completed ALCs are not cached but fetched on request. If you have lots of unfinished ALCs this may take a while.
