### ISSUE TITLE
apiv4: Do not display completed stations for started LABs

### ISSUE THREAD

**Issue by GerneCacher** [mirsch/lab2gpx#142]
Hello,
in apiv4 **completed stations** are listed when ‘Include partially completed labs’ is selected.
A switch to deselect completed stations would be nice. Then you will only see open stations for started LABs.
In apiv3 this was the case via ‘Exclude your findings, copy & paste source code of your findings page:’

Thank you

**Comment by mirsch** [comment]
duplicate of #140
