### ISSUE TITLE
Gefundene Labs kennzeichnen

### ISSUE THREAD

**Issue by gcey** [mirsch/lab2gpx#144]
In https://gcutils.de/lab2gpx/apiv3/ gibt es die Funktion "Funde nicht ausschließen sondern als gefunden markieren".
Sie bewirkt, dass bei den gefundenen Labs "`<sym>Geocache</sym>`" durch "`<sym>Geocache Found</sym>`" ersetzt wird.

In https://gcutils.de/lab2gpx/ finde ich diese Funktion nicht.
Ich hätte angenommen, dass das bei Verwendung von "Öffentliche GUID für den API-Abruf" automatisch geschieht.
Aber leider ist das anscheinend nicht so.

**Comment by mirsch** [comment]
"Komplett abgeschlossene Labs einschließen" ruft die Funde mit ab und markiert sie entsprechend

**Comment by gcey** [comment]
Ja, für komplett abgeschlossene Labs funktioniert es, aber für teilweise abgeschlossene nicht.
Auch da sollten die gefundenen Standorte als gefunden markiert werden.

**Comment by keenonkites** [comment]
Ich habe das selbe Problem:
- für abgeschlossene Labs werden die gefundene als 'gefunden' markiert
- für angefangene Labs habe ich keine Möglichkeit gefunden die 'gefundenen' einzelnen Station auch als 'gefunden' zu kriegen. 

Anders herum gesagt: Das Markieren als gefunden funktionert zwar gut für die abgeschlossenen aber es fehlt für die angefangenen.

**Comment by gcey** [comment]
@mirsch: Siehst Du die Chance, das zu korrigieren?

**Comment by mirsch** [comment]
die sollten ab jetzt als gefunden markiert werden, wenn ihr beides ankreuzt "Komplett abgeschlossene Labs einschließen" und "Teilweise abgeschlossene Labs einschließen"

Da kommen aber auch die nicht gefundenen der teilweise abgeschlossenen ALCs mit raus. 

Das ist etwas unglücklich, weil die 3 Schalter direkt auf den API filter gehen (praktisch die gleiche Funktion wie in der original App) und die Logik für "als gefunden markieren" dann da drauf setzt.  Das ist etwas verwirrend und es gibt aktuell keine Möglichkeit ausschließlich gefundene auszugeben. Wenn ich Zeit habe werde ich das bei Gelegenheit noch etwas umbauen

**Comment by keenonkites** [comment]
Für mich passt das so, habe es soeben getestet.

Nun funktioniert es wieder so wie ich es gewohnt war und, auch wichtig, so wie ich es gerne hätte.

Besten Dank für die Korrektur.

**Comment by gcey** [comment]
Ist perfekt. Danke!
