### ISSUE TITLE
API Version 3 switch

### ISSUE THREAD

**Issue by Billy-Wallace** [mirsch/lab2gpx#147]
Could you please make it an option to always use the API V3 form saved as a cookie please.

If the form is given new values and then you switch API versions, those values are lost.

Thank you.

**Comment by tohaase** [comment]
Thumbs up. Same here. Some macros for [GSAK](https://gsak.net/index.php) doesn't work anymore, because API v4 will be used and if you click to switch to v3 pre-populated checkboxes and textareas will differ. 😢

It would be great if there would be an option to force API v3. 👌

**Comment by SamHenkel** [comment]
Smart ass addendum:
Actually we are talking about the Api V1: https://labs-api.geocaching.com/swagger/docs/v1
and there about the Search V4: /Api/Adventures/SearchV4
Conclusion: There are no Apis V3/V4

**Comment by tohaase** [comment]
You know it better than us. I know. 👍😊

But that's what the user "outside" sees when the form opens.

![IMG_20240504_001725.jpg](https://github.com/mirsch/lab2gpx/assets/75227177/fcdc6d13-a374-4b99-a257-aea73bf50ac6)

When it has been named API v4 and v3, I call it so. Maybe technically wrong, but so everyone knows what we're talking about. 😏

**Comment by Billy-Wallace** [comment]
No need to make any modifications to the form. The problem is prevented by adding your v3 query string to the URL.
