### ISSUE TITLE
Will not download

### ISSUE THREAD

**Issue by Ambegador** [mirsch/lab2gpx#148]
Tried to download for current location and get prompted to enter GUID which I did. Still prompts for GUID.

**Comment by Ambegador** [comment]
Screenshot of error message
![Screenshot_20240503_124945_Chrome](https://github.com/mirsch/lab2gpx/assets/168858192/4616679e-3c8c-4e8c-b1c9-89a6f69a6c1e)

**Comment by tohaase** [comment]
Well... check [here](https://en.wikipedia.org/wiki/Universally_unique_identifierv) to know what a guid is. It's not your username, it's an unique id. 😊
