### ISSUE TITLE
Koordinaten Eingabe / Kartendarstellung

### ISSUE THREAD

**Issue by retep-55** [mirsch/lab2gpx#152]
¡hola!

wenn ich auf der Karte einen Punkt markiere, werden die Koordinaten entsprechend geändert. Umgekehrt leider nicht. Wenn ich Koordinaten Eingabe wird der Kartenausschnitt nicht angepasst.
Wäre super, wenn das geändert werden könnte.

Die neue Version ist super, weil man nicht mehr den Quellcode der Seite mit den eigenen Funden eingeben muss.
Glückwunsch zu dieser Lösung.

Toll wäre es, wenn man man wahlweise wieder die Anzeige der Tagebucheinträge bekommen könnte. Nicht grundsätzlich, aber mit einen Wahlfeld mit Haken.

Eine andere Sache wäre, ALCs an einer Route zu finden. Die Umkreissuche ist die eine Möglichkeit, verursacht aber, zumindest bei mir, manchmal unnötigen "Beifang". Gut, kann man löschen, aber mit einer Route wäre es eleganter. Ort A nach Ort B, Breite des Korridors und schon hätte man eine gezieltere Suche. Alternativ mit einem Polygon. Ich weiss aber nicht, was einfach zu programmieren, bzw. umzusetzen ist.

Vielleicht sind die Gedanken hilfreich.

Saludos
Peter

**Comment by Mioncz** [comment]
Although it is no longer necessary to enter the source code of the actual found page, this unfortunately makes it impossible to tag partially found labs. :-(
See isuue #149.

**Comment by mirsch** [comment]
> wenn ich auf der Karte einen Punkt markiere, werden die Koordinaten entsprechend geändert. Umgekehrt leider nicht. Wenn ich Koordinaten Eingabe wird der Kartenausschnitt nicht angepasst. Wäre super, wenn das geändert werden könnte.

duplicate of #32


> Toll wäre es, wenn man man wahlweise wieder die Anzeige der Tagebucheinträge bekommen könnte. Nicht grundsätzlich, aber mit einen Wahlfeld mit Haken.

die Funktion wird nicht wider kommen. Das wurde in #88 ausführlich beschrieben

> Eine andere Sache wäre, ALCs an einer Route zu finden. Die Umkreissuche ist die eine Möglichkeit, verursacht aber, zumindest bei mir, manchmal unnötigen "Beifang". Gut, kann man löschen, aber mit einer Route wäre es eleganter. Ort A nach Ort B, Breite des Korridors und schon hätte man eine gezieltere Suche. Alternativ mit einem Polygon. Ich weiss aber nicht, was einfach zu programmieren, bzw. umzusetzen ist.

Die API von GC bietet diese Funktion nicht und wir speichern die ALCs nicht in einer Datenbank o.ä. so das wir so eine Funktion nicht abbilden können. Grundsätzlich ist hier an Filtern/Abfragen nur das möglich, was auch in der originalen App möglich ist. Ggf. weniger, aber auf keinen Fall mehr
