### ISSUE TITLE
Make zip file

### ISSUE THREAD

**Issue by BlueAngel61** [mirsch/lab2gpx#155]
Why does the "make zip file" function not work in the new version?
To create a zipped download, I have to click on the old version every time.

**Comment by mirsch** [comment]
can not reproduce. please provide the settings used

**Comment by BlueAngel61** [comment]
Hallo, ich versuche ein Ticket zu schreiben. Leider verstehe ich nicht, was zu machen ist. Ich wollte nur mitteilen, dass ich in der neuen Version keine Labs hinzufügen kann. Nur mit der alten Version ist das möglich. Dazu brauche ich ja die gezippte Datei.Am 07.06.24, 08:30 schrieb mirsch ***@***.***>:

   
  can not reproduce. please provide the settings used
