### ISSUE TITLE
API-Doku

### ISSUE THREAD

**Issue by gcey** [mirsch/lab2gpx#167]
Das ist eigentlich keine issue, sondern eine Bitte/Frage:
Wo ist das Adventure Lab API V4 dokumentiert, das von lab2gpx verwendet wird?

**Comment by SamHenkel** [comment]
https://labs-api.geocaching.com/swagger/ui/index#!/Adventures/Adventures_SearchV4

**Comment by gcey** [comment]
Vielen Dank!
