### ISSUE TITLE
Bonus-Infos klar ersichtlich

### ISSUE THREAD

**Issue by bonstetten** [mirsch/lab2gpx#17]
Bei einem meiner LabCaches erscheinen erscheinen die Bonus-Koordinaten im Klartext als "Award information". Dies sollte nicht so sein.
Wer kann das abstellen? Ist ja nicht die Idee hier alles zu spoilern!

**Comment by mirsch** [comment]
Das ist eher ein konzeptionelles Problem in der API. Beim Abrufen des Adventure Labs werden die Journaleinträge (Award Message und Image) mit ausgeliefert. Besser wäre es von seitens Groundspeak das erst zu senden, wenn die richtige Antwort eingegeben wurde, aber das können wir nun mal nicht ändern und bei den Sofaloggern ist das auch schon lange bekannt.

Die Nachricht hier weg zu lassen würde das Problem nur verschleiern, nicht beheben.

Wichtig ist, in den Journaleinträgen keine Hinweise zur Antwort oder zum Bonus zu geben.
Ich mache es bei meinem Lab so, dass man sich die Antwort merken/aufschreiben muss und dann im Listing vom Bonus erklärt wird, wie man aus den notierten Antworten die Koordinaten berechnet. Ich kenne auch viele, die die Antworten der Reihe nach bei Certitude.org eingeben lassen um an die Bonus Koords zu kommen.
