### ISSUE TITLE
Feature request - output in format for Cachetur.no Bulk Add Waypoints

### ISSUE THREAD

**Issue by vpdjgeo** [mirsch/lab2gpx#19]
Would love to have output in format so I can directly import into Cachetur.no for trip planning

Semicolon delimited - Format:

Waypoint name;Waypoint type*;Coordinates;Comment

Waypoiint Name = name of AL stop
Waypoint Type = lab
Coordinates = lat long
Comment = Lab Cache Name

**Comment by mirsch** [comment]
Whats wrong with GPX Import?
https://cachetur.atlassian.net/wiki/spaces/EN/pages/519241729/GPX+import

**Comment by vpdjgeo** [comment]
They only import geocaches - not lab caches - they do a lookup based upon the GC Code value to get the geocache details.
Since lab caches do not have GC Codes - they fail to import.

As an interim, I have created a Perl script to take your GPX output and output the Bulk Add Waypoint format.

**Comment by mirsch** [comment]
included in last release.
