### ISSUE TITLE
Übersetzung nach Englisch

### ISSUE THREAD

**Issue by ThomGr** [mirsch/lab2gpx#2]
Es wäre super wenn das Tool auch auf Englisch verfügbar wäre, im Zweifel einfach einen Button auf eine Kopie der Seite. Den Text kann ich bei Interesse beisteuern, ich mache auch die deutsche Lokalisierung für Cachly

**Comment by mirsch** [comment]
Wenn im Browser die bevorzugte Sprache auf Englisch gestellt ist, dann wird das Formular in Englisch angezeigt

**Comment by ThomGr** [comment]
Ok, perfekt. Hatte den Tipp für die Seite aus dem Cachly Betatester-Chat und war schon überrascht dass die sich gar nicht über die Sprache gewundert hatten 😉
