### ISSUE TITLE
Lab stage 'question' not updated in tool download

### ISSUE THREAD

**Issue by PlasmaWave** [mirsch/lab2gpx#20]
mirsch ... I ran the tool to update my local area, as several new Labs had been published, but noticed a problem with some info in the download not being updated.

About a week ago I had to change the question for one stage of my own Labs, but todays 'lab2gpx' download still shows the 'old' question. I ran the tool several times after changing various settings (e.g. with/without my own Lab finds included), but still the old question showed. In case the change of question is not detected by the browser tool until at least one user logs that stage, I asked a local cacher to log that stage (changed zone limit temporarily) - they saw the 'new' question and the Official Lab App accepted the new answer as correct. I ran the browser tool after they logged the stage but still see the old question.

Ran the GSAK macro, which shows the 'new' question correctly.

Any thoughts?

https://labs.geocaching.com/goto/loughborough_tour

**Comment by mirsch** [comment]
this is because data is cached for faster (repeated) requests, but cache is never cleared.

**Comment by PlasmaWave** [comment]
Thanks mirsch ... can the user clear the cache (if yes, how?) or does your script need modifying?

Would be great if this could be resolved as I only picked the issue up by chance, looking at one of my own Labs.

**Comment by PlasmaWave** [comment]
Many thanks ... my example now shows the 'new' question

**Comment by mirsch** [comment]
cache is cleared every 24 hours now
