### ISSUE TITLE
Lab-Bonus

### ISSUE THREAD

**Issue by wurschtbrot** [mirsch/lab2gpx#23]
Hallo,
bin leider technisch nicht sehr versiert, aber wäre es möglich, die Bonus-Caches zu Lab-Runden mit in die GPX zu übergeben, sofern in der Lab-Beschreibung ein GC-Code steht?
Vielen Dank für das hilfreiche Tool!
Beste Grüße

**Comment by mirsch** [comment]
Das ist leider nicht möglich, da die Informationen auf geocaching.com oder der API nur zur Verfügung stehen, wenn man eingeloggt ist.
