### ISSUE TITLE
Show Stations as Waypoints

### ISSUE THREAD

**Issue by capoaira** [mirsch/lab2gpx#25]
It would be nice to have an option to show the labcaches as wps/stations of an Adventure.
For more background to this issue: https://github.com/cgeo/cgeo/issues/10558

**Comment by jakedot** [comment]
Hello @mirsch, please see the discussion regarding the options for GC Code prefixes in the cgeo/cgeo#10911 issue I linked to above - maybe if you decide to implement something for this issue, you could generate the caches in the GPX containing the lab caches as waypoints with an "AL" prefix instead of an "LC" prefix.

**Comment by mirsch** [comment]
> Hello @mirsch, please see the discussion regarding the options for GC Code prefixes in the [cgeo/cgeo#10911](https://github.com/cgeo/cgeo/issues/10911) issue I linked to above - maybe if you decide to implement something for this issue, you could generate the caches in the GPX containing the lab caches as waypoints with an "AL" prefix instead of an "LC" prefix.

You can already change the prefix as you like. See https://github.com/mirsch/lab2gpx/issues/12
User the option "Code prefix" and change it to "AL"

**Comment by Herr-Ma** [comment]
This issue would be  be a great improvement. In my "old" own solutions i create all labs with the stations as waypoints. For now i have to write a converter to do that. It would be much easier, if this tool will do it ;-)

**Comment by mirsch** [comment]
did some refactoring today so adding new export formats becomes much easier

**Comment by mirsch** [comment]
"Zipped GPX with Waypoints" and "GPX with Waypoints" are now available as export formats. Let me know if this works for you. It seems not to work in Cachly on iOS but Looking4Cache does. Also c:geo looks good at the first try

**Comment by Herr-Ma** [comment]
Funktioniert leider nicht in GSAK

Damit es klappt, muss der Tag <desc> mit dem Inhalt (HasChildren) vor den <ept>-Tags eingefügt werden. Wichtig ist, dass der Taxt HasChildren in Klammern vorhanden ist. Also:
   
            <name>Adventure Labs</name
            <desc>(HasChildren)</desc>
            <wpt lat="51.308333333333" lon="9.5021666666667">

Weiterhin ist html im <cmt>-Tag bei Unterwegpunkten nicht vorgesehen. Der Text ist dafür auch viel zu lang und würde auf einem Garmin-Gerät nicht angezeigt werden.

Lösungsvorschlag: In der LongDescription erst den Text des AdventureLabs und dann Abschnittweise den der Stationen (ggf. inkl. Frage und Antwort) unterbringen. In den Waypoints selber dann als <cmt> nur die Frage.

Ich hänge mal eine gpx-Datei eines AdventureLabs an, so wie ich das mal umgesetzt habe...

[ALDocumenta.gpx.zip](https://github.com/mirsch/lab2gpx/files/6718425/ALDocumenta.gpx.zip)

**Comment by Herr-Ma** [comment]
Statt (HasChildren) geht übigen auch 

<desc>This is an individual cache generated from Geocaching.com</desc>

**Comment by mirsch** [comment]
Ich habe die Beschreibungen wie vorgeschlagen angepasst

**Comment by Herr-Ma** [comment]
Laden der Stationen als Wegpunkte funktioniert in GSAK jetzt einwandfrei! (Sehr gut 👍)

In der Darstellung (long_description) fehlt zwischen dem Titel der Station und dem Text "Frage" noch ein Zeilenumbruch. Ich persönlich würde auch die Frage nicht zusammen mit der Stationsüberschrift darstellen, sondern erst unter der Stationsbeschreibung, aber das ist Geschmackssache...

**Comment by mirsch** [comment]
da war ein HTML Tag nicht richtig geschlossen

**Comment by mirsch** [comment]
scheint jetzt alles zu funktionieren. Ich schließe das hier bei Problemen ggf. neues Ticket aufmachen

**Comment by Herr-Ma** [comment]
Jepp - funktioniert!

**Comment by Herr-Ma** [comment]
Darf ich mir noch was wünschen? 

In GSAK werden die Wegpunkte in einer anderen Tabelle gespeichert, als die Caches selber. In dieser Tabelle selber kann man jetzt nicht erkennen, ob die Stationen linear zu spielen sind, oder nicht. Hier wäre es schön, wenn der Code ( = \<name>-Tag) des Wegpunktes auch das L vorangestellt bekommt, falls der Lab linear ist.

D.h. statt \<name>01abcd\</name> einfach \<name>L01abcd\</name>

**Comment by Herr-Ma** [comment]
...und könntest du ggf noch die eindeutige Id des AdventureLabs im gsak-Feld "UserData" mit exportieren? Somit hätte man auch lokal eine eindeutige Verbindung zwischen den gefundenen Labs und den AdventureLabs (wichtig für gsak-Makros, die für die Founds auch die Koordinaten benötigen)

/<gsak:UserData>61c2f36f-a7d5-416f-96a8-a685145e4b0f</gsak:UserData>

**Comment by Herr-Ma** [comment]
Im Grunde genommen ist auch der Titel des AdventureLabs, der zusätzlich in den Überschriften der einzelnen Stationen dargestellt wird, obsolet.

**Comment by jakedot** [comment]
Ja, aber nur für die Generierung als Waypoints. Als Caches braucht man es logischerweise.

**Comment by jakedot** [comment]
> D.h. statt <name>01abcd</name> einfach <name>L01abcd</name>
> 
> Tut keinem weh, ist aber auch auf einem Garmin device extrem hilfreich, da dort die Wegpunkte überhaupt keinen Zusammenhang zu den Caches selber habe. Somit würde man dort auch sofort sehen, das die Reihenfolge wichtig ist.

Tolle Idee, ich trage das nach c:geo, danke!

**Comment by Herr-Ma** [comment]
> 
> 
> Ja, aber nur für die Generierung als Waypoints. Als Caches braucht man es logischerweise.

Da hast du vollkommen Recht. Ich bezog mich dabei natürlich nur auf die Generierung als Waypoints...

**Comment by mirsch** [comment]
Ich bin der Meinung, dass einige Anwendungen z.B. Looking4Cache aus dem Code des Wegpunktes und dem Code des Caches die Hierarchie ableiten.
C:geo macht das z.B. auch so, wenn die GSAK Erweiterung für Parent nicht im Wegpunkt enthalten ist (leider - bis auf 2 Ausnahmen - hard coded auf "GC") https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/files/GPXParser.java#L303
Also Code des Caches, die ersten beiden Zeichen entfernen, Code des Wegpunktes die ersten beiden Zeichen entfernen, wenn der Rest dann überein stimmt ist der Wegpunkt ein Kind des Caches.

Den Code des Wegpunktes können wir daher nicht ändern.

**Comment by Herr-Ma** [comment]
Dann könnte man ja die ersten beiden Zeichen des Codes statt 01, 02, ... mit S1, S2, ... für 'nicht lineare' und L1, L2, .. für lineare AdventureLabs ersetzen (wenn die Nummerierung hexadezimal erfolgt, klappt es auch bei den wenigen AdventureLabs mit 10 Stationen).

Wenn im GPXFile der \<desc>-Eintrag "This is an individual cache generated from Geocaching.com" lautet, kann übrigens auch die gsak-Parent Erweiterung entfernt werden.

**Comment by mirsch** [comment]
> Dann könnte man ja die ersten beiden Zeichen des Codes statt 01, 02, ... mit S1, S2, ... für 'nicht lineare' und L1, L2, .. für lineare AdventureLabs ersetzen (wenn die Nummerierung hexadezimal erfolgt, klappt es auch bei den wenigen AdventureLabs mit 10 Stationen).

ja, so könnte es klappen

> Wenn im GPXFile der <desc>-Eintrag "This is an individual cache generated from Geocaching.com" lautet, kann übrigens auch die gsak-Parent Erweiterung entfernt werden.

Ich denke nicht, denn dann wird es in c:geo nicht mehr funktionieren, da der Prefix dort wie gesagt auf "GC" hard coded ist.
Mich wundert eher, das GSAK seine eigent Parent Erweiterung nicht versteht und noch das <desc> Tag auswertet. Aber vielleicht stammt die auch nicht von GSAK. Ich habe das bisher nur bei OC gesehen.

**Comment by Herr-Ma** [comment]
> Ich denke nicht, denn dann wird es in c:geo nicht mehr funktionieren, da der Prefix dort wie gesagt auf "GC" hard coded ist.
> Mich wundert eher, das GSAK seine eigent Parent Erweiterung nicht versteht und noch das Tag auswertet. Aber vielleicht stammt die auch nicht von GSAK. Ich habe das bisher nur bei OC gesehen.

Das wundert mich. Ich habe gerade die GPX-Datei von einem Cache bei GS runtergeladen. Dort lautet der \<desc>-Eintrag des GPX-Files \<desc>This is an individual cache generated from Geocaching.com\</desc>. Der Waypoint hat beim \<name> den Prefix S1 (nicht GC). Dieses GPX-File funktioniert einfandfrei in gsak als auch in c:geo.

**Comment by mirsch** [comment]
> Das wundert mich. Ich habe gerade die GPX-Datei von einem Cache bei GS runtergeladen. Dort lautet der <desc>-Eintrag des GPX-Files <desc>This is an individual cache generated from Geocaching.com</desc>. Der Waypoint hat beim <name> den Prefix S1 (nicht GC). Dieses GPX-File funktioniert einfandfrei in gsak als auch in c:geo.

Der Code des Caches beginnt aber mit GC. Wenn Du das durch "LC", "AL" oder was auch immer ersetzt funktioniert es nicht mehr

**Comment by Herr-Ma** [comment]
Ah, ok - das war mir neu, da ich maien Krams immer aus gsak exportiere. Dann ist natürlich 'HasChildren' und der gsak-Parent-Tag vorhanden. Somit ist der Prefix des Caches egal...

**Comment by mirsch** [comment]
- [x] eindeutige Id des AdventureLabs im gsak-Feld "UserData"
- [x] die ersten beiden Zeichen des Codes statt 01, 02, ... mit S1, S2, ... für 'nicht lineare' und L1, L2, .. für lineare AdventureLabs ersetzen
- [x] Im Grunde genommen ist auch der Titel des AdventureLabs, der zusätzlich in den Überschriften der einzelnen Stationen dargestellt wird, obsolet.

**Comment by Herr-Ma** [comment]
Die letzten beiden Punkte funktionieren wie gewünscht (Klasse Arbeit!).

Das gsak-Feld UserData mit der Cache-Id ist allerdings nicht vorhanden. Wenn ich das im Code richtige sehe, machst du das abhängig von der Linearität der AdventureLabs und der ausgewählten Art, wie mit linearen ALs umgeggangen werden soll. Das Feld sollte immer vorhanden sein...

**Comment by mirsch** [comment]
> Das gsak-Feld UserData mit der Cache-Id ist allerdings nicht vorhanden. Wenn ich das im Code richtige sehe, machst du das abhängig von der Linearität der AdventureLabs und der ausgewählten Art, wie mit linearen ALs umgeggangen werden soll. Das Feld sollte immer vorhanden sein...

Du hast vollkommen recht

**Comment by Herr-Ma** [comment]
Perfekt! 

Ich hoffe, du hast nicht zu viel Arbeit. Aber da dein Tool im Moment das Einzige ist, was noch funktioniert, ist es derzeit sehr gefragt. Und mit mehr Anwendern kommen natürlich auch mehr Wünsche und Fragen ;-)

**Comment by fm-sys** [comment]
> > Der Waypoint hat beim  den Prefix S1 (nicht GC). Dieses GPX-File funktioniert einfandfrei in gsak als auch in c:geo.
> 
> Der Code des Caches beginnt aber mit GC. Wenn Du das durch "LC", "AL" oder was auch immer ersetzt funktioniert es nicht mehr

Das können wir gerne in c:geo anpassen. Wir (c:geo team) wollen definitiv kein Hinderungsgrund für die weitere Verbesserung dieses Services sein... 

Auch Pull Requests sind bei c:geo immer willkommen ;-)

**Comment by jakedot** [comment]
OT:

> Tolle Idee, ich trage das nach c:geo, danke!

> Das können wir gerne in c:geo anpassen. Wir (c:geo team) wollen definitiv kein Hinderungsgrund für die weitere Verbesserung dieses Services sein...

Wenn man etwas nicht zum cgeo#cgeo/team trägt, kommt das Team eben und holt es sich! 😇

**Comment by SamHenkel** [comment]
> 
> 
> ...und könntest du ggf noch die eindeutige Id des AdventureLabs im gsak-Feld "UserData" mit exportieren? Somit hätte man auch lokal eine eindeutige Verbindung zwischen den gefundenen Labs und den AdventureLabs (wichtig für gsak-Makros, die für die Founds auch die Koordinaten benötigen)
> 
> <gsak:UserData>61c2f36f-a7d5-416f-96a8-a685145e4b0f</gsak:UserData>

Das ist leider gar keine gute Idee, denn das UserData-Feld ist für Daten des Users und sollte nicht von einem GPX-File überschrieben werden. Zumal es im Table "Caches" der GSAK-Datenbanken ein eindeutiges Feld "guid" dafür gibt. Die fälschlich in das Userdata-Feld eingetragene guid macht leider viele GSAK-Makros unbrauchbar. Das ist sehr ärgerlich und sollte vermieden werden.
Hans

**Comment by Herr-Ma** [comment]
@SamHenkel: Du hat Recht, es gibt in der GSAK-Tabelle Caches das Feld guid, welches von gsak auch als "Geocaching.com Cache Guid" beschrieben wird. Da diese guid allerdings weder in gsak angezeigt wird, noch von Groundspeak in GPX-Dateien exportiert wird, ist es irgendwie an mir vorbei gegangen. Ich habe den Eindruck, dass weder Groundspeak noch gsak dieses Feld nutzt. Daher bietet es sich natürlich an, diese guid für die uuid zu nutzen, und sie nicht in gsak:Userdata, sondern in gsak:Guid zu exportieren.

Im übrigen finde ich das du ein wenig übertreibst. Einserseits schreibst du, dass das UserData-Feld für Daten des Users ist, und andererseits, dass "viele GSAK-Makros" unbrauchbar werden. Da stellt sich mir doch glatt die Frage, warum denn "so viele" Makros auf ein Feld zugreifen, dass für Daten des Users gedacht ist - da liegt dann wohl ein fälschlicher und ärgerlicher Zugriff seitens der Makros vor ;-)

Übrigens kannst du beim Importieren einer GPX-Datei in GSAK das Feld UserData vor dem Überschreiben sichern ...

**Comment by SamHenkel** [comment]
[...] Im übrigen finde ich das du ein wenig übertreibst. Einserseits schreibst du, dass das UserData-Feld für Daten des Users ist, und andererseits, dass "viele GSAK-Makros" unbrauchbar werden. Da stellt sich mir doch glatt die Frage, warum denn "so viele" Makros auf ein Feld zugreifen, dass für Daten des Users gedacht ist - da liegt dann wohl ein fälschlicher und ärgerlicher Zugriff seitens der Makros vor ;-)
> 
Makros eines Users könne natürlich auf die Userdaten zugreifen (in der Regel lesender Weise). Das wird häufig für das Erstellen von filtern in der Tourplanung verwendet.
> Übrigens kannst du beim Importieren einer GPX-Datei in GSAK das Feld UserData vor dem Überschreiben sichern ...
Die Möglichkeit des Lockens von Feldern beim Import ist mir bekannt. Danke

**Comment by mirsch** [comment]
see https://github.com/mirsch/lab2gpx/issues/41
