### ISSUE TITLE
Viewing question..?

### ISSUE THREAD

**Issue by itommyjay** [mirsch/lab2gpx#26]
Hey Mirsch! 

I'm sorry but I didn't find any other way to contact you other than posting this 'issue'. I'd just like to ask a question about viewing. If you know how to message me on github, go for it. I didn't figure it out. I'm an avid geocacher struggling to find a way to logically get  at many of Prague's (and during travel other countries ALs). Somewhere on reddit I found a link to this project. 

I have in theory (and in my limited knowledge) found it very usefull to plot AL locations on a map, which isn't really possible in the map. I have, in the past, used GPX files to import GS data into Google Maps. I'm on iOS, so I don't know many other options for me to view these while in terrain. I tried using your app and CAN impost the data into Google Maps, but once there, I don't know how to get 'back to the AL'. In other words, the locations are there, but no link or reference to the AL app. I've tried on laptop and on app, but there's no link or reference to the AL. the code which is used as the name does not link back to the AL in an internet search.

Futhermore, I tried other online applications like https://www.gpsvisualizer.com/ to get read the data. On their website, when I click on a location, it does lead me directly to the link which gets me to the app. Nonetheless, this website didn't seem to work well away from HC.

Do you have any recommendations to make this work for an iOS user, AFK? I'd be happy to get your feedback on using your *very useful web app* AFK. I do not* own a GPSr, only an iPhone.

Any help would be much appreciated. I think this is not only an awesome project, but one incredibly useful.!!! Hope you manage to contact me back! Looking forward to hearing from you!

Tommy

**Comment by mirsch** [comment]
I'd recommend to use a geocaching App like Cachly (this is what I use for geocaching anyway) or Looking4Cache (free, but I dont like the UI)
You can import the (zipped) GPX file and view it on the map (even at the same time as the geocaches, that's exactly what I built this tool for). 
If you open the the Cache description there is a link which will bring you directly into the Adventure Labs App.

Here is an Screenshot of Cachly. The light white bluish markings are the Adventure Labs, the red triangle is a sign for corrected coordinates (usually used for solved unknown caches) but for Adventure Labs it indicates that they have to be processed in a certain order if you select "As corrected coordinates" for the "Linear Adventure Labs" option.


![21-05-25 08-57-45 3158](https://user-images.githubusercontent.com/6177906/119453447-bad05b00-bd37-11eb-8755-8e65d06f2225.png)

**Comment by itommyjay** [comment]
Hi Mirsch!

Thanks so much for your quick reply! I’ve purchased Cachly and will give it a shot. Thanks!!
