### ISSUE TITLE
Found LABs

### ISSUE THREAD

**Issue by JustusTwo** [mirsch/lab2gpx#27]
Hi
I have recently found this resource and used it successfully quite a few times over the past few weeks. Today I have used it but it is returned the output with my finds. 
I have cleared the box several times and tried putting in my source from my finds but it continues to return my finds. I then tried to mark the box (Do not exclude my finds but mark as found) but it still returns the finds without marking them as found. 
Ken

**Comment by mirsch** [comment]
Please upload you source here: https://gcutils.de/lab2gpx/found.php this will give you a hash of your upload.
Give me this hash and I'll look into it

**Comment by JustusTwo** [comment]
Thank you 
Thanks. Your hash: 5264c85b96b27376bb5b109f54a2562a

**Comment by mirsch** [comment]
Could not reproduce the problem so far.
Please provide the exact settings you are using including coordinates and name an example Lab you expect to be excluded but it is not

**Comment by JustusTwo** [comment]
No I cannot reproduce it either. I have ran several areas where I have found lab sets and none are being returned. Well no longer an issue. How odd. 
Thank you for looking at it,
