### ISSUE TITLE
Error message - no caches

### ISSUE THREAD

**Issue by forest-ghost** [mirsch/lab2gpx#28]
Hello,

I am trying to use lab to gpx. I keep receiving the error message that there are no caches. I have set the coordinates to be at the location of a known AL and set radius to 200 km. I tried messing around with the other settings but keep receiving the same error. Cords N38 35.579 W090 21.570

**Comment by cghove** [comment]
I believe Groundspeak have closed the API

**Comment by mirsch** [comment]
> I believe Groundspeak have closed the API

you are right.
they have built in a kind of application level authentication. The good news is that it still works without a login. We only need a consumer key...

**Comment by mirsch** [comment]
ok, we're back in the game.

**Comment by forest-ghost** [comment]
Thanks for getting it working again, I really appreciate it!

Ethan

________________________________
