### ISSUE TITLE
Limits vergrößern

### ISSUE THREAD

**Issue by ThomGr** [mirsch/lab2gpx#3]
Es ist klar dass es Limits für den Radius und die Anzahl der Labs geben muss. Trotzdem wäre schön, wenn es Werte größer werden könnten. Für andere Länder wäre es schon hilfreich wenn der Radius größer wäre, weil die Dichte an Labs nicht so groß ist.. Natürlich geht dann die Wartezeit hoch, aber das kann man ja mit einem Hinweis erläutern.
Falls das Problem die API von Groundspeak ist: man kann die Anfrage ja in mehreren API calls aufteilen. Das macht Cachly ja auch in ganz vielen Stellen

**Comment by mirsch** [comment]
Das Problem ist, dass es keine offizielle API gibt.
Die API calls sind praktisch nur durch Traffic Monitoring herausgefunden und die aktuellen maximal Werte sind die, die ich in der original App beobachten konnte.

Aufteilen wäre sicher eine Möglichkeit das Problem zu umgehen.

**Comment by ThomGr** [comment]
Das ist mit bewusst, sonst  hätte Cachly die API schon längst implementiert. Aber ob reversed oder offiziell: am Ende ist es eine API. 
Ich weiß, aufteilen ist viel Aufwand, wenn die Koordinateneingabe einfacher ist kann man das ja auch ganz gut manuell machen.  Der Radius war nur die erste Kritik aus Übersee 😉

**Comment by mirsch** [comment]
der Radius scheint in der API nicht eingeschränkt zu sein.
Ich komme mit 20.000 Km auf aktuell 23.036 Labs ;)
Und ich habe den Paging Parameter gefunden. Der ist - wer hätte es gedacht, der gleiche wie in der API für die Caches.
Man muss also nur über das Resultset blättern, dann könnte man theoretisch alle runter laden.

Den Radius sollte man auch direkt in Km eingeben, nicht in Metern

**Comment by ThomGr** [comment]
Super!

**Comment by mirsch** [comment]
Radius in Km max. 20.000
Paging ist eingebaut, limit aktuell bei 1.000 (auch wenn 500 im Form steht)
Die API ist aber sehr langsam beim Abrufen der Details, so dass es sehr lange dauert.
Ich denke, mehr als 1.000 Labs machen auch keinen Sinn. Das werden immerhin rund 5.000 Caches im GPX.

**Comment by ThomGr** [comment]
schöne Verbesserung, mehr macht aber wegen der Dauer der Abfrage wirklich keinen Sinn
