### ISSUE TITLE
No Uppercase of FirebaseDynamicLink

### ISSUE THREAD

**Issue by Herr-Ma** [mirsch/lab2gpx#30]
You are using the FirebaseDynamicLink to Create the 'Code'. The FirebaseDynamicLink is case sensitive, in case of that converting to upper cases is a bug.

**Comment by mirsch** [comment]
it's used the generate the code and has nothing to do with Firebase afterwards, so case doesn't matter.
As stated in the comment, this may produce collisions if there are similar links which are different in upper/lowercase only, but I'm pretty sure most of the Geocaching apps and devices will ignore case in the code and you'll have the problem on the other side.
Let me know if you have a better idea to generate a reproducible unique code

**Comment by Herr-Ma** [comment]
I know that the chance is small, but if there are actually two labs with a FirebaseDynamicLink in the generated GPX file, which only differ in upper and lower case, then the first one will be overwritten when loading in GSAK or Garmin devices (both differ large and small letters in the code).

So why not avoid a possible error right away and use the original code LCaBcD instead of LCABCD (example)?

**Comment by mirsch** [comment]
ok, did not know GSAK and Garmin are case sensitive in code, I expected the opposite.
Thing is: if I change this now it will generate duplicates if one import the new codes in an existing "Database" of Labs. But may be this is no problem at all

**Comment by Herr-Ma** [comment]
What about a checkbox for "generate Code case sensitive [  ]" with default = unchecked ?

**Comment by Herr-Ma** [comment]
Great - Thanks!

...oder wahrscheinlich eher: Danke!
