### ISSUE TITLE
Add settings as parameters to url 

### ISSUE THREAD

**Issue by Herr-Ma** [mirsch/lab2gpx#34]
Cool wäre es, wenn man seine Einstellungen gleich als Parameter an die URL hängen und den Download automatisch starten könnte. Somit könnte man einen festen Link speichern und sich so sofort seine Daten downloaden (also im Grunde genommen analog zu dem API-Aufruf). 
Ich habe mir bisher immer alle Labs aus den Umgebungen zweier verschiedener Koordinaten gezogen. Wenn man diese an die Url hängen könnte, müsste man nicht immer neu seine Einstellungen verändern.

Bsp: https://gcutils.de/lab2gpx/index.php&latitude=51.12345&longitude=10.67890&radius=5000&take=100&type=Lab&prefix=LC&format=zip&check=1234&StartDownload

**Comment by Willabee** [comment]
This is a great idea. As Groundspeak have now decided not to give access to the API it would allow me to download all caches in an area using GSAK macro and then pass as parameters the same location and radius to get the labs within the same area.

**Comment by vohe** [comment]
This is an old one, but it would be great do make it possible.
As user of Android(App's) i could do a URL-Shortlink to my mobile, which opens a webside.
In case i could do something like https://gcutils.de/lab2gpx/index.php?coordinates=52%2010.100, 08%2011.111&take=10
it would be much nicer to handle this.
In that case i guess, it would be possible to transfer my actual coordinates into the lab2gpx webside from e.g. my navigation software .

please think about to make that possible

**Comment by mirsch** [comment]
nope, sorry
