### ISSUE TITLE
gpx mit den bereits gefundenen Lab-Caches

### ISSUE THREAD

**Issue by grummelot** [mirsch/lab2gpx#40]
Die Erzeugung einer PQ mit x Lab-Caches, die sich in einem Radius von y km um das ausgewählte Zentrum befinden, klappte hervorragend und war wesentlich schneller, als aufgrund des Hinweises zu erwarten war.

Da mich jedoch nur die bereits von mir gefundenen Lab-Caches interessieren - Groundspeak zählt zwar die Lab-Caches bei der Zahl der Founds mit, berücksochtigt sie jedoch nicht in der Found-PQ -, habe ich die von lab2gpx erzeugte Datei (auf Basis der Lab-Cache-Liste aus meinem GC.com-Profil) nach Laden der gpx-Datei manuell in GSAK ausgewählt *), den Status auf "gefunden" gesetzt, sowie das Found-Datum eingetragen. Einen Weg, Last-Found und Last Log nachzutragen, habe ich leider nicht entdeckt, was - so meine Vermutung - zur Konsequenz hat, dass diese Caches vom GSAK-Makro FindStatGen3 nicht berücksichtigt werden.
*) die Selektion musste ich manuell vornehmen, da mich nur die Lab-caches aus der letzten Tour interessierten (die vorangegangenen hatte ich bereits mit einem, derzeit - aufgrund von Rechteproblemen - nicht mehr funktionierendem GSAK-Makro geladen.

Optimal wäre daher eine Option in lab2gpx, um nur die bereits gefundenen Lab-Caches - in dem von der GC.com-Found-PQ gelieferten Format - als gpx-Datei herunter zu laden.

mit freundlichem Gruß und vielen Dank für das lab2gpx-Angebot

**Comment by SamHenkel** [comment]
[...] Einen Weg, Last-Found und Last Log nachzutragen, habe ich leider nicht entdeckt, [...]
Dan  hast Du vermutlich nicht richtig gesucht. FSG braucht Fund-Logs für die Statistik. Für das Erzeugen dieser Logs gibt es extra ein [GSAK-Makro (hier klicken)](https://gsak.net/board/index.php?showtopic=6527&view=findpost&p=246496)
Hans

**Comment by grummelot** [comment]
@SamHenkel: vielen Dank für den Tipp (hatte zwar bereits zuvor in der GSAK-Makro-Library nach einem entsprechenden Makro gesucht, vermutlich jedoch mit den falschen Suchparametern - peinlich). Makro lief durch und das Feld "letzter Log" wurde gefüllt, letzter Found jedoch weiterhin ohne Wert ... ob sich daranFindStaGen stört (die betr. Lab-Caches wurden nämlich auch jetzt noch nicht berücksichtigt)

![GSAK](https://user-images.githubusercontent.com/87673677/126326798-f25d4b7f-38a4-4fda-96f3-d1f386ed33ec.jpg)

**Comment by geocat87** [comment]
> Die Erzeugung einer PQ mit x Lab-Caches, die sich in einem Radius von y km um das ausgewählte Zentrum befinden, klappte hervorragend und war wesentlich schneller, als aufgrund des Hinweises zu erwarten war.
> 
> Da mich jedoch nur die bereits von mir gefundenen Lab-Caches interessieren - Groundspeak zählt zwar die Lab-Caches bei der Zahl der Founds mit, berücksochtigt sie jedoch nicht in der Found-PQ -, habe ich die von lab2gpx erzeugte Datei (auf Basis der Lab-Cache-Liste aus meinem GC.com-Profil) nach Laden der gpx-Datei manuell in GSAK ausgewählt *), den Status auf "gefunden" gesetzt, sowie das Found-Datum eingetragen. Einen Weg, Last-Found und Last Log nachzutragen, habe ich leider nicht entdeckt, was - so meine Vermutung - zur Konsequenz hat, dass diese Caches vom GSAK-Makro FindStatGen3 nicht berücksichtigt werden.
> *) die Selektion musste ich manuell vornehmen, da mich nur die Lab-caches aus der letzten Tour interessierten (die vorangegangenen hatte ich bereits mit einem, derzeit - aufgrund von Rechteproblemen - nicht mehr funktionierendem GSAK-Makro geladen.
> 
> Optimal wäre daher eine Option in lab2gpx, um nur die bereits gefundenen Lab-Caches - in dem von der GC.com-Found-PQ gelieferten Format - als gpx-Datei herunter zu laden.
> 
> mit freundlichem Gruß und vielen Dank für das lab2gpx-Angebot


eine Option nur bereits gefundene Labs abzurufen würde ich mir auch wünschen :)

**Comment by mirsch** [comment]
mit V4 Api ist es jetzt möglich nur die gefundenen abzurufen
