### ISSUE TITLE
Top-Up Missing Adventure Labs

### ISSUE THREAD

**Issue by Willabee** [mirsch/lab2gpx#44]
When you 'Exclude your finds, by copy and paste source code of your finds page:', your code must scrape the source code to extract the AL IDs so that they are not downloaded. I assume you use something like an XPath or RE expression to extract the IDs.

What would be the minimum markup your code needs to extract those IDs?

This would allow me to not only exclude finds but also exclude previously downloaded ALs, so as to top-up any missing ones.

I could easily produce the code containing the existing and found IDs but I need to know the minimum markup for your code to function correctly.

Wish list would be to supply a comma separated list of AL IDs to exclude from the download.

**Comment by SamHenkel** [comment]
I pretty much like this idea.

**Comment by mirsch** [comment]
there is a new field in the exclude section called "UUIDs to exclude". Add a list of Ids you want to exclude there. Separate by comma, semicolon or new line. This should work using the Id of the entire adventure lab to exclude all stations of this lab, as well as the Id of a station to exclude this station only.

**Comment by geocat87** [comment]
https://github.com/mirsch/lab2gpx/issues/44#:~:text=I%20could%20easily%20produce%20the%20code%20containing%20the%20existing%20and%20found%20IDs%20but%20I%20need%20to%20know%20the%20minimum%20markup%20for%20your%20code%20to%20function%20correctly.

How can you produce such a list of IDs? using GSAK? a little tutorial would be nice ^^.

**Comment by SamHenkel** [comment]
> 
> 
> #44.
> 
> How can you produce such a list of IDs? using GSAK? a little tutorial would be nice ^^.

The GSAK help file should be sufficient. Here is your code (assumed your guids are written to user2):
`	MFilter Where=cachetype="Q" and user2<>""
	$data = sqlite("sql","Select user2 from caches WHERE (rowid in (select * from gridtemp))")
	MsgOK Msg=$data
	Clip Data=$data	`

Hans

**Comment by SamHenkel** [comment]
> 
> 
> > #44.
> > How can you produce such a list of IDs? using GSAK? a little tutorial would be nice ^^.
> 
> The GSAK help file should be sufficient. Here is your code (assumed your guids are written to user2):
> ` 
MFilter Where=cachetype="Q" and user2<>"" 
$data = sqlite("sql","Select user2 from caches WHERE (rowid in (select * from gridtemp))") 
MsgOK Msg=$data 
Clip Data=$data `
> 
> Hans

**Comment by SamHenkel** [comment]
Leider wird der Code in den Code-Tags nicht korrekt dargestellt (Absätze werden einfach entfernt.)
Deshalb jetzt mal so:
	MFilter Where=cachetype="Q" and user2<>""
	$data = sqlite("sql","Select user2 from caches WHERE (rowid in (select * from gridtemp))")
	MsgOK Msg=$data
	Clip Data=$data	

Hans

**Comment by geocat87** [comment]
> Leider wird der Code in den Code-Tags nicht korrekt dargestellt (Absätze werden einfach entfernt.)
> Deshalb jetzt mal so:
> MFilter Where=cachetype="Q" and user2<>""
> $data = sqlite("sql","Select user2 from caches WHERE (rowid in (select * from gridtemp))")
> MsgOK Msg=$data
> Clip Data=$data
> 
> Hans



sorry, aber mit der Nutzung von MFilter und sqlite kenne ich mich überhaupt nicht aus :/
da muss ich wohl drauf hoffen, dass es vielleicht mal ein Macro dazu gibt ^^

**Comment by SamHenkel** [comment]
**Das ist fertiger Makro-Code**. Da mußt Du dich nicht auskennen. Erstellen ein Makro (Menü>Makro>Neu), kopiere den Code, sichere das Makro, laß es laufen.

**Comment by geocat87** [comment]
achso, ok. hab nicht kapiert, dass das ein fertiger Macro Code ist. O.o 
hat funkioniert, danke, musste nur noch user2 durch userdata ersetzen, weil die guids bei mir in den Benutzerdaten stehen.

**Comment by SamHenkel** [comment]
Wenn ich die guids in das UUID-Feld kopiere und das Tool laufen lasse, bekomme ich einen 403-Fehler.

**Comment by Willabee** [comment]
I believe UserData gives the IDs of the Lab Stages, not the IDs of the Adventure Lab that would be required.

If one of the User fields could be supplied with the Adventure Lab ID (or to UserData instead of the Lab stage ID) then Han's code would give you the correct IDs on the clipboard ready to paste in to the UUID exclude text area.

**Comment by geocat87** [comment]
it works for me with the IDs of the Lab Stages. so I can exclude 4 stages of a Lab and only get the missing stage. 

Is there a way to write the  Lab Stage IDs into the userdate from a gsak database that was imported via the ImportAdventureLabs Macro?

**Comment by geocat87** [comment]
in the gpx created by lab2gpx yesterday the stage IDs were written in the userdata field after importing into GSAK, this does not work with gpx files that were created today :/

**Comment by GithubMarcel** [comment]
maybe because of https://github.com/mirsch/lab2gpx/issues/41

**Comment by geocat87** [comment]
> maybe because of #41

you are right! thanks, I missed #41 ^^

**Comment by SamHenkel** [comment]
Gibt es ein Limit für guids?

**Comment by geocat87** [comment]
> Gibt es ein Limit für guids?

scheint so... mit 100 hat es funktioniert, mit 150 nicht....

**Comment by Willabee** [comment]
Looks like the UUID is a moving target!!!

You can fix your GSAK database and Replace UserData with Guid or vica versa to suit. It's probably best to update Guid if you already have the IDs in UserData, as that is what has been decided here.

   $_sql="Update or Replace Caches SET Guid=UserData"
   $status=Sqlite("sql",$_sql)
   RESYNC

There is a limit of 100 IDs, which probably corresponds with the API 'take' parameter max of 100 set by Groundspeak.

That is why it would be better to use the Adv Lab IDs rather than the Lab stage IDs. Every Adv Lab ID equals 5 Lab stage IDs on average.

**Comment by SamHenkel** [comment]
From today the guid is written to the field where it belongs to. Großes Dankeschön.
The guid also is part of the url (at least valid for the newer Labcaches. Just use "g_right(url,36)" instaed of user2 or userdata in my code snippet.
