### ISSUE TITLE
Gefundene Lab GCs werden nicht als gefunden geladen

### ISSUE THREAD

**Issue by Donsen64** [mirsch/lab2gpx#47]
Leider werden die gefundenen Lab GCs die bei mir nach dem 21.07.2021 gefunden wurden nicht mehr mit als gefunden geladen bzw. beim Laden ignoriert. Könnte dies mit der API Änderung im Zusammenhang stehen mit der auch das GSAK Makro ImportAdventureLabs.gsk zu kämpfen hat? 

Zusatzinformation: Nach dem 21.07.2021 hatte ich welche gefunden die sich nicht in dem, über die Koordinaten ausgewählten Kreis, befinden.

**Comment by mirsch** [comment]
neue Version mit API V4 ist online. Gefunden wird jetzt bei der Suche berücksichtigt
