### ISSUE TITLE
Duplicate Labs ?

### ISSUE THREAD

**Issue by travels4jack** [mirsch/lab2gpx#5]
Hi there,

Frequent traveler between France and Belgium (worldwide when the COVID 19 restrictions will be lifted) I intend to create a unique list of Labs (potentially 2 if the number of Labs is too high to be handled).
With the limitations in radius and number of Labs retrieved through your macro, will any duplicate Lab appear twice in my list ?
(assuming there is an overlap in my search between 2 geographically distant locations ?)
Thanks

**Comment by mirsch** [comment]
Can't you just create 2 lists and choose the appropriate list depending on where you are?

**Comment by travels4jack** [comment]
This is indeed a solution.
Considered it as an option although I preferred to have them on one list.
Not a big deal I will adapt accordingly.
Thanks
