### ISSUE TITLE
Land und Region im GPX

### ISSUE THREAD

**Issue by bergolo** [mirsch/lab2gpx#54]
Hallo
Wäre es vielleicht möglich im GPX auch <groundspeak:country> und <groundspeak:state> zu liefern?
Sonnige Grüsse

**Comment by mirsch** [comment]
Die information ist in der API von den Adventure Labs nicht enthalten. Mit GSAK kannst Du das nachträglich einfügen.
This information is not provided by the API. Use GSAK to add it afterwards
