### ISSUE TITLE
deaktivierte Labs werden nicht mitgezählt

### ISSUE THREAD

**Issue by maartzee** [mirsch/lab2gpx#57]
Hi, 
ich habe z.B: 2019 einen Adventure-labcache gefunden, der mittlerweile deaktiviert ist. Dieser wird mit seinen 5 Stationen nicht als Fund angezeigt / gespeichert, obwohl er in der Adventure Labcache Finds Liste drin steht.Allerdings sind dort die Station ausgegraut, nicht wie bei den anderen farbig. (siehe Bild)... Kann man da was machen?
![Labs](https://user-images.githubusercontent.com/89810229/132092664-6a3b111f-e44b-4143-bcf5-fb2d4ea87b25.jpg)

gruß maartzee

Das Programm ist super genial !

**Comment by mirsch** [comment]
sollte sich mit v4 erledigt haben
