### ISSUE TITLE
Is there a limit? 

### ISSUE THREAD

**Issue by ghost** [mirsch/lab2gpx#58]
Thank you so much for this tool. 
It's a mess that there is no tool from groundspeak to get all the Adventures into my geocaching software as gpx file.  So i got all german labs from the webside, with a small python tool. 
But as a did that i ask me if there is limit (for lab per second) at your tool?

Regards
Vo.

**Comment by bergolo** [comment]
Ciao vohe
Darf ich dein "small python tool" vielleicht mal testen?
Viele Grüsse, Walter

**Comment by mirsch** [comment]
don't!
