### ISSUE TITLE
Adventures können nicht mehr als "gefunden" markiert werden

### ISSUE THREAD

**Issue by Summersunny123** [mirsch/lab2gpx#59]
Neuerdings können die adventures Labs nicht mehr als gefunden markiert werden. So bleiben sie auch auf der cgeo Live Karte weiterhin sichtbar. Vorher hatten die Labs einen weißen Hintergrund. Nun ist er braun. Was kann ich tun um die gespielten Labs in der live Karte von cgeo wieder auszublenden?

**Comment by wojciech-wroblewski** [comment]
I spent last 30 minutes fighting with this issue (comparing XML files) after throwing A LOT of swear words last time I was on LAB cache spree. Finally I've worked it out.

It seems c:geo allows you to mark labs as read based on the GC code prefix. The LAB posted coordinates it loads automatically start from "AL", while the Lab2Gpx toll by default sets "LC". Setting the prefix to "AL" while generating the file seems to do the trick.
![Screenshot_20211228-182038_Samsung Internet](https://user-images.githubusercontent.com/28697792/147591598-c086cac1-e814-4e88-8e84-287bdf039a69.png)
![Screenshot_20211228-182618_cgeo](https://user-images.githubusercontent.com/28697792/147591616-fc0eeb1f-6d42-4bb9-a169-61328ed6e81f.png)

**Comment by jakedot** [comment]
see cgeo/cgeo#10911 and cgeo/cgeo#11718

**Comment by mirsch** [comment]
> see [cgeo/cgeo#10911](https://github.com/cgeo/cgeo/issues/10911) and [cgeo/cgeo#11718](https://github.com/cgeo/cgeo/issues/11718)

thanks, added a note to the prefix option.
