### ISSUE TITLE
Add 'button' to centre map on current location

### ISSUE THREAD

**Issue by PlasmaWave** [mirsch/lab2gpx#6]
Is it possible to add a selection 'button' to centre the map on users current location?

Particularly when travelling (after Covid-19!) it would be really useful to have the map showing your current location before running the script. At present, with the map being centred in Germany, the user either has to scroll the map or find current co-ords. Tapping the map would be so much easier and quicker.

I use GSAK and have the 'ImportAdventureLab' macro, which works really well, but your 'script' is much quicker and easier ... superb for when travelling outside your normal area - GSAK option needs to be carried out back home. 

I have successfully imported generated gpx files from this script into 'Looking4Cache' app and 'Memory-Map' ... really quick and easy! Well done and many thanks.

**Comment by mirsch** [comment]
there is now a link to get your current location

**Comment by PlasmaWave** [comment]
Works perfectly, many thanks.
