### ISSUE TITLE
Adventure Lab Activity

### ISSUE THREAD

**Issue by knumbles** [mirsch/lab2gpx#61]
A feature that I would find useful for each adventure is a list of user names that had completed the Adventure. It would then be possible to find Labs that friends had not done when planning a trip out.

**Comment by Herr-Ma** [comment]
Unfortunately, this is not possible as there is no function for this feature in the Groundspeak API for AdventureLabs.

**Comment by knumbles** [comment]
Thank you for your quick reply.
