### ISSUE TITLE
Skip

### ISSUE THREAD

**Issue by ghost** [mirsch/lab2gpx#64]
Can a Skip value be added to the form as an option to include in the API call please?

**Comment by Willabee** [comment]
Any feedback on whether or not to implement adding a skip field to the API request URL so that a radius from a specific centre location can easily be extended please.

**Comment by Billy-Wallace** [comment]
This would be a great feature to include and gets my vote.

**Comment by Rhoenbussard** [comment]
I like to use the macro to download the adventurelabs. So it would be fine to skip the caches

**Comment by mirsch** [comment]
this tool is not intended to use for automated downloads.
