### ISSUE TITLE
Remove 'S' number from Lab title PLUS concatenate main Lab title with Stage title

### ISSUE THREAD

**Issue by PlasmaWave** [mirsch/lab2gpx#7]
A huge enhancement to the imported gpx file would be to display the main Lab 'Title/Name' concatenated with the Stage 'Title/Name', separated by a character & spaces (e.g. ' : '). Presently the user cannot see the stage title/name until that stage is opened. This concatenation works really well with the GSAK 'ImportAdventureLab' macro.

After importing the gpx file into the caching app, stages of all Labs imported are listed in 'S' number order, which means all S1, then all S2, then all S3, etc. To see the 5 (or 10) stages of a specific Lab grouped together, the user needs to perform searches and/or filters. The 'S' number is generated by the script and is not part of the Lab or Stage title ... there doesn't appear to be any advantage of having the 'S' number, which actually makes sorting difficult.

Many thanks for a great feature.

**Comment by mirsch** [comment]
The S number in the name shows the order intended by the owner - this is important, especially with linear labs.
The new format is now:
Lab title : Snr. Stage title
This sorts like you want it but keeps the S number.

**Comment by PlasmaWave** [comment]
Looks very good and has solved the 'sorting' problem, many thanks for the fast solution.

Stages definitely do need to be numbered for linear Labs, but not sure it is essential for 'any order' Labs ... however the solution is fine and the 'S' prefix no longer interferes with main sorting and is good for linear Labs. Concatenating the two titles is definitely working well.
