### ISSUE TITLE
Alle eigenen Funde ein ein gpx exportieren

### ISSUE THREAD

**Issue by Saarfuchs** [mirsch/lab2gpx#75]
Für die Statistik wäre es ganz nett, wenn man den Quelltext der Anzeige der eigenen Funde von labs.geocaching.com in eine Textbox kopieren könnte und anschließend eine gpx-Datei exportiert wird, welche nur die eigenen gefundenen Labs enthält. Wäre hilfreiche bei GSAK und der eigenen Statistik.

Die Schwierigkeit sind wahrscheinlich die Labs der verschiedenen Mega-Events, die nur wenige Tage spielbar sind?

Viele Grüße
Jörg
www.saarfuchs.com

**Comment by bcas008** [comment]
würde ich mich auch darüber freuen :)
