### ISSUE TITLE
creating a gpx only with already started Adventures

### ISSUE THREAD

**Issue by djbrieflos** [mirsch/lab2gpx#78]
If i have some already started Adventures in a zone (eg. a bigger city) and I want only to finish them without starting new adventures, it will be very useful, if I can create a gpx only with started Adventures = all these adventures, whereof I solved at least one, but not all labs.

Nochmals auf Deutsch :-) 
Es wäre hilfreich, wenn man eine GPX nur mit den bereits begonnenen Adventure Labs in einem Gebiet erstellen könnte, damit man diese gezielt fertig stellen kann.

**Comment by mirsch** [comment]
neue Version mit API V4 ist online. damit ist das jetzt möglich
