### ISSUE TITLE
How can I use the "exclude own finds" function on my smartphone (Android)? Browser crashes

### ISSUE THREAD

**Issue by berndy2001** [mirsch/lab2gpx#80]
Hello,

thanks for the tool, it works fine on desktop. Now I would like to use it on the go, but unfortunately it is not so easy. Chrome does not paste the copied source code, Firefox crashes and with Opera I don't have the possibility to select the whole source code. Apparently too much text.

My idea would be to write a self-hosted script that logs me in in the background, parses the IDs of the finds and outputs them. I would then copy these into "Exclude UUIDs".

Step 1 (login) is done, but I can't handle the IDs. The UUID is probably for the whole adventure, not for the single station.
And the tool can't do anything with the ID I find in the html-source

`<div class="key-photo-thumb" style="background-image: url(https://gsmediadata.blob.core.windows.net/mediacontainer/2de48147-4197-4a2e-90c8-f5690aa5d9ad)"></div>`

Thank you in advance.

**Comment by edgarbriggs** [comment]
Same here, "exclude own finds" causes crash of browser. Tried Firefox and Chrome (Android). It might be a browser Problem, but maybe someone has an idea how to prevent this.

**Comment by berndy2001** [comment]
Since I had no better idea, I solved it as follows:
a php script logs me in and outputs the source code. I can copy this (only works in Firefox) and use it as usual.

**Comment by mirsch** [comment]
new version using api v4 is online. no need for copy & paste anymore.
