### ISSUE TITLE
Not All Adventure Labs Returned from Query

### ISSUE THREAD

**Issue by BBofG** [mirsch/lab2gpx#82]
I set up a query on the webpage and find that not all Adventure Labs are returned. You may replicate this issue by completing the following:
General location = 43.668, -79.306
Radius = 5km
Max caches = 100
Exclude owners, finds, UUIDs = Leave blank
The data returned will include A "Hoppy" Craft Tour by BK649nBK73 but NOT include Queen of the Beach by Spidermonkey09. This is but one replicable example, 

Great tool btw, thanks for creating it.

**Comment by SamHenkel** [comment]
Raise the radius to 6 kms. There is no issue with "Queen of the Beach"

**Comment by BBofG** [comment]
I actually had it set to a much higher value. It wasn't picked up yet
others much farther away were.

**Comment by BBofG** [comment]
Currently not able to replicate.

**Comment by mirsch** [comment]
unable to reproduce
