### ISSUE TITLE
Bookmarklet for getting Lab UUIDs

### ISSUE THREAD

**Issue by rragan** [mirsch/lab2gpx#86]
I made a bookmarklet for extracting lab UUIDs from the Found Labs page. No need to do a View source. The output is in a new tab already selected and ready to copy/paste into the UUID text area.  

The source code to allow easy install of the bookmarklet is here:
https://github.com/rragan/rragan.github.io/blob/main/FoundLabsIdBookmarklet.html

To try it Run my new tool and drag the link to your bookmark bar.
https://rragan.github.io/FoundLabsIdBookmarklet.html

 Then Go to https://labs.geocaching.com/logs and let it load fully. Click the bookmarklet created and a new tab should open with all the Id's of your Found Labs highlighted and ready to copy to the clipboard. Paste this into the UUID section of the labs2gpx page and they will be excluded. 

It's only been tested on my own finds and it worked ok. Long term, maybe your site should host the installer as the HTML of the page may change and you already would have to deal with that in your View Source parsing code. Feel free to do so. It's not a lot of code

**Comment by Khoda1** [comment]
Not sure what to do to make this work. How do I run the source code contained in the first link.

**Comment by palzkillm** [comment]
Haven't tried it out yet, but from the technical approach, this should also solve the issue of found, stages appearing as undfound again after beeing renamed, documented here: https://github.com/mirsch/lab2gpx/issues/83

**Comment by palzkillm** [comment]
Tried it - with the string in the UUID field, the application will return HTTP 500. Without it, it will work. Original string below.

> c1a3127a-b9bc-482b-83de-2a8629497e2c,b49394bc-44ce-4590-bf2f-20fac9b9c533,473f0e23-c3e4-4f40-ace8-302d413a6f5d,6a0f461a-4125-4c79-9e61-882b91c1ef87,4eb51e61-8507-4c48-9b59-9eb0bf7cda4a,598336d5-09c9-4579-b473-6182e6b3f0c1,9cc1edc5-304a-4149-b55a-1b0b480e89e9,251621e5-d9a4-4bfc-9be8-c209eacd0b98,4712ec8b-a0aa-4702-96b5-e6b9aaa2301d,dc41f438-6c80-4181-9e79-22ce78ee63b9,32a4c62b-e13c-4976-9aa0-565b06bf393f,bef7ba4d-7c42-4624-84e2-ca16433d5385,0cb8df0d-8b0e-473e-9861-c8d160a68e96,9806623b-fb26-451f-8dc2-be5eb8ab0150,130b518a-7680-4ac1-a11f-e8e2bbc65d83,245045f4-3f2f-4667-a597-d9d2aeb55bb2,2a45fa3a-7e1e-4ade-8d2e-a26011c0757c,bee70699-7748-4554-b331-05f31918f437,c308fd15-e0ef-4935-9940-563318baf6bb,5f2a2064-f54a-4399-93c2-524e8cefb33a,37e383d0-3382-461e-8383-19a28db670d1,407fd30e-91ad-4387-80f7-8660141b2c21,f0a88d13-e38a-44b1-8980-c642e586c85b,b8b1d990-7ce9-4c9f-ab78-c50c9fb1ca4b,347f30f7-9c70-4dbd-aab5-bb42893658ef,7c6c7687-dae3-45ac-b3c4-1363c7cd2848,24af08cb-8d80-4e99-aa5f-220a73292869,b9421e2b-d64e-4fbb-9104-2c4e51dbfc27,448e79c3-0ad6-48fc-9ea9-2fc6d569e44e,79864825-238b-4c7e-8da6-7efdf37589ee,7541ceae-a4e4-4b5c-bb33-7d8a224c912e,c04ef72a-b2ee-410f-9189-1cf7ab237baa,a145c48c-7a4d-4457-b2cc-ea8fbf0dd7ed,3ee524d0-0256-4d5a-8ced-2f6206efa202,3464c258-4d94-4fcb-ae84-b3cd402d62c5,ab9254db-118e-4518-ad6f-1007c3a3d256,5e8d12e0-5948-4468-aa05-31551ce260a2,453ddacd-d301-4230-a777-4a4d2650b7e7,308f0344-7647-4085-b632-877827168a4a,911aa5d6-6cfb-40d8-9a72-543e94311944,8ca239de-3d6f-4f15-8e53-7327913fceac,cc0ec390-6bdb-41a9-9c78-ea2a3eacebf6,5b2d6415-341f-4fee-89ab-f6de0e1ea155,cc2dfbe7-6f3b-4697-9d94-29f7be6f462b,e235c18d-2b19-434e-a45d-217403fc6c5e,4a15208b-05e8-4c26-b741-6ee5bd86ad4f,d7a28647-904a-4479-98b4-2665d11e08f0,d4d77b9e-453a-43b3-ac1b-3592293803e6,2a2b0130-f40e-46ac-8196-2e99d5fd53db,9e33ed6f-04b0-4ece-a153-436c44f29d59,0c7bfb52-f1e6-469b-8510-89275893c9fa,dd8e5fa4-d53a-4ad9-b013-97b1ab10e8e4,6014ffc3-ed8d-456f-a3b1-5a8d7829186f,4b0df105-8d18-4cf8-89eb-9a89239cf957,32cbcff0-2973-41d5-b6de-4a5b023a3cd6,422edf3a-23af-47a7-afb9-6d79c9a569cc,de5a2dac-b286-4fda-9eb3-0d4a7732bb56,f5c64bc3-b969-4bfa-a187-404a4f95c531,a478ffcf-b15a-4fa0-a7c4-628b67a97be9,7630da7d-8cac-48c2-96db-3c1d9eeb9d83,fe01e03e-901d-4c59-9c35-76116bf0d8f2,ef240aa9-2506-41b8-baf9-4c40a48c26ea,2f1cb834-9a76-4f1c-bd3a-bd10f63e6ef6,ca69cd02-bc8f-453a-848b-9e67ae59df27,6266ac0a-3c69-40b4-b6a0-054a483fcfa0,64aab85d-6422-4dd8-bff4-f4cfed25887a,9aa2c639-7906-4aa0-a22b-9ccc260517c5,0bc28327-53db-4e9e-9ea5-9cb84a606e51,706d005b-4ae6-4e5c-ac0e-a76238e5e769,a4088c7f-82e3-4da5-b741-4346e5970c60,e7e73639-cc3a-434f-8411-c1a95eb78db2,a1ac902a-32fe-4691-a8d9-5da018b9e4d9,ba7d0cfd-3499-47f7-8d33-922d286e706b,2733ed8d-16dd-46b5-b497-b4a8e4b5aed0,2d635512-17c1-4232-9392-c956f6db6a11,05715a54-14da-4509-ad05-1640cfea9e0d,a5ed8e2c-725a-4d2e-a4fd-d48d400235ca,f005ef44-8abd-4ec0-842a-90c4bae40487,71980a55-0216-4c32-8b46-e87e26624c17,9c61bfef-8047-4501-900f-d2fbb2b9e4ce,c3b4d0a6-2a7d-4842-859a-212ee4080ab4,35f34d5b-e453-4944-b4ae-97260e648422,174f3a2b-4d01-4ddf-9bcb-6071ea36cfe2,afdfb5fd-3f34-42ea-9e4e-88c557f7b014,18a0a085-89d5-4745-a8a7-b4343a8796de,fa1e1f04-7b3f-404e-a32d-a0570ac33f0b,c5b37454-0c15-4fb0-8a88-93f6afdbb44a,4d237cf1-2091-425b-8be3-7495cf580daf,1850f046-d7e3-4e1b-8ee9-8ff2f031e3a9,27abd6a3-3ace-4036-9b9b-11c42b4dede1,cec66edb-616d-4adb-8638-535c3c7b7108,8ef2f4d1-2726-4915-9960-2186c5114e7c,6a221b31-f05f-4e8c-8345-125d3b96a9de,05bf8a8c-8ec2-458f-821c-8842f782ca36,004fd30f-75d8-4381-83c5-1e9e1c01062c,a21fad14-650e-4de2-9777-9fba876ad2b0,d51027b1-4a14-45ff-99cb-a8fed8c8867f,bc1d4d5f-5905-4d81-920c-d23a64ab698b,38a1af8d-33d5-453a-b6a5-7eb16ad790b6,9ce9736c-c085-4029-bbce-5d40f1a6aec7,a07f87a6-c538-490b-9fd2-14b6bd52c192,8e12e708-d94e-40f8-af9e-3fc8f2261f4d,2f2792e6-f8f6-45dd-9f4f-5379fe1d00a8,bae36335-0a10-4b01-bfb7-827a68d78f70,e222a167-7bb7-4186-8487-464392ddb299,f12751ee-f19c-4946-b09f-404a48e0a24d,7d182596-904b-46b5-9fc2-489b97bbb536,7909c77b-e494-47c8-b1e9-d102b34a4820,5cd7d3bd-500a-4299-ab6d-ab35a0ad12f5,f3ed162c-49f9-4668-abc2-b5eda561eed8,da887220-9cca-4407-a8c1-c18e0af6d6ec,d6983906-1d4a-42c8-8a84-e2cafcb415ac,b133a066-5ef0-4f8c-bf09-b19ddebfa56c,5ef05d67-6b03-4e30-a29d-87fdc7f25fe8,6f921c13-0ce0-478a-9f5c-d919c3443955,615c2bfc-c01d-4a3b-b5a1-9b04934963a2,c18d09b3-87f3-4348-b005-e67a41104bb9,dd7d221e-0ef8-4aae-bd4c-6f9a70d5ba4a,81745f2e-13f1-4486-8825-0f8311c788d8,77237b9d-7bc4-4392-b656-c3bdd8882ad0,71aeb44e-1c8a-4008-b231-a22344c2b38b,3badc2f1-7782-4cc9-a68a-6792b1c8974d,5cfb16c8-a02f-4ff0-9bee-9bb9c37ba623,d0f81ce0-a50b-4c7d-a705-b740fc308b59,8018c89b-daae-4b5d-a057-c7454e51a973,d36cfb90-c1ce-4f96-9180-422b649c8f9f,7be995e0-a1ab-4d90-b69e-6a4649db4f09,ff8d3e86-5c88-486c-9ef2-0a417be54521,f730e7c2-50dc-450c-9d56-c0c9c1780f45,ace2607f-7385-423c-951f-a6b1ee74e676,4bd5f377-9bd3-44cc-99b4-ef3d7cb21117,147e6d98-3f33-4749-84d8-2dc65a0d6a12,afd18eba-7d14-478b-9016-ef96d6d16c61,56527f5e-6f96-4410-adf6-777bad9ad8e4,e0c540bf-cee4-4f4d-9a39-cb200724581b,b25bd8c8-3c90-44bc-9c6c-70794f1bd761,8998a8f3-7271-426f-a22b-3eaad269b400,552a06eb-2c1a-49c2-bfbf-ffb80c75d5c9,75fb4a0a-1875-4ec4-97a4-d7794f209564,1ac49bcb-39a2-48de-854f-646ee7c9121c,8308b54b-f475-4d26-8a81-0d4b63a2487b,5d406ade-13a4-4d78-8808-56d6226362e1,34de8001-5fbd-4219-bf08-483245cf0895,d1004834-9c64-4451-ac42-450d168b4914,c5443114-40b7-4f44-a7cd-e0dde4b4d74d,efc2acd1-a5a5-4e14-b016-564da43f5ac1,8a447075-261e-46d9-96c9-e82c5684c59e,cc7868a8-105e-497f-9587-3ef459ab0287,e9610c34-d214-4c8b-bdd5-37bf4798c0df,f8d3a955-67ab-498c-a30a-328b27680940,dbf6d739-1f48-4923-86e7-ea84fceae78e,c4c482a6-f052-4e2a-b7a9-08a2cca173b3,a1768d21-3fa1-4ff0-b7c2-61689d9e6327,a5f5b8a7-a73a-4d60-875b-7ac2c7644c85,e0b8d168-7082-4547-8653-7f02cccd22ec,23f61662-b902-42c7-8417-871f700aba28,502268e3-a7d8-42e6-8454-f78ad24228be,9b34e729-3dd0-48ac-a5cb-e0f67fbf61f8,61300aad-e8c1-4c53-8318-dd3cdc96478a,6b6da959-458f-4f5c-80f1-261ddffc74e3,565862ae-b793-47b2-bf4c-cfb1880f9e1d,9ccef00d-f950-4f8d-978a-d20d0c81fd9a,1a078539-22fe-4041-86d2-e037e12e12af,8142bdc6-be32-464c-a2ae-7d30b8124f21,62ac2d1b-731c-4619-8aba-d02d231e1a41,66618b7b-7181-4155-8260-d136e01f4f29,fa8ee5f7-63b5-4699-bc8e-56bc21f0145f,2e84eddb-fbf4-47c7-a137-40b5037694d4,e0f6b337-339d-4727-8f25-63b64ac219ad,af7c9fb4-776a-48fc-ad8d-6777305ad17a,7df75c11-b46d-48b5-a52d-76c924d1950d,2db5a541-240b-4f32-aa0e-f3c6f29eee37,d93dc7ab-b7d7-4ec4-a1dd-1f4d805d5066,6fb55fa6-6fb2-4b5e-a246-298c112d2cb8,52a526c2-2f63-4c09-adac-33a7fdca1b64,702283cf-99d8-4f54-b7df-646ef44e2a00,813f9827-fe43-4a0c-aa01-5c21dc84dd07,eeaa3b0e-7dcb-4ffe-ae51-1de471c36b5d,03ab7b79-e0c0-4c7e-a46f-6fa4bae953ea,f6e6af27-5f34-433b-bd17-a92fcbed5e02,51061607-dddb-433e-99fd-f7815e7511d2,42b10f02-cea5-4d89-a62d-d5b054e3ae83,b22a3292-cbf3-42e1-a063-f7f9424eede8,553bbf1f-352d-4407-80f8-02ec8e8561cd,2e4a11a6-7c16-4443-962c-529e51c8697b,064639a6-e386-48ad-8642-ebfa6cee1384,4f58ce27-db1d-41f9-b546-cc57171bee04,1a6bf7d0-1026-4c97-8e6e-c4fd4afd18b2,1a6b0770-a3f2-454b-ad29-ad32a3efe749,92d29354-381b-4153-a9f0-42dbf1eeeee3,81e35a4b-95e5-43dc-8369-8f6a1b6e7bd7,85951d67-0bf5-4222-b815-ba8333b45ce2,34d61c41-4b32-4886-90a7-2fcb3588d3d6,1a87a2c3-e2c9-4231-abd7-10ef897a1b42,acacbcbd-60e1-43ec-9b21-d8e6de250561,08eaf411-7cbd-4492-a828-7d4bb58df532,1f40fe6c-7126-47f6-aa17-9b3c6e61c2ef,90f82d7a-e210-4a97-8876-f0eaa3e7cf52,129c9f28-24c7-4afc-852f-9dc481fc3222,f1677974-4f4e-4b98-a3b0-b544a8b9d5b1,3f51299e-c90a-4580-9c68-033384d0ae15,ebf731f4-d4e3-4c73-8d86-501161eb5045,137627b2-cc3b-4c1f-8c12-a537e341d297,82bbfa90-4539-41dd-b7b2-e8ad7a1b9094,40b993b5-c17e-4a00-b5bf-23c6df0dc076,916abd84-3343-419d-a22a-123301ca3577,3849da8b-693a-4225-b639-112ef2a37cf2,6987f1da-def0-4c84-93a1-7a7968d73350,49bb7a29-b6ab-497f-bfd6-81b59797ec24,b3d304aa-0c2d-4211-8160-41b8dbe4bc09,729b932e-ac8e-41ea-8053-5f3bedccdf57,1a45ba5e-2f84-4a6a-858a-c2e6382b99c3,93a569de-c461-4b74-ae9a-1e4f7f376e36,b388febc-a87c-414e-8c2c-7b66670a8409,7e905422-014b-4f0e-b534-def30b4225df,6c3b832b-323b-4960-a170-bffa1ce990c3,3f94fa3a-82d6-4f18-a6a8-9d7042270d33,f676a156-85f2-4c2d-91c5-072f8d715203,1ebba39d-90e7-404a-8af2-0bd5d63d8812,b1078bf8-4b1b-4304-9b52-b096d18056da,c5460325-7062-44ca-bb20-3fcf0baca370,c4767290-ed1f-4a68-bcfd-3b7275c4ce55,98680eae-7bcd-45ad-8fd3-4cd6a9c800ea,4575cea8-182a-4fd1-ada1-3e7174317b0b,0f0cdefd-9fcb-4b60-b374-eacbf9c4c4e7,b3fa7e51-d316-41e5-9105-86e09f051b6b,b2d41c13-22f0-48b4-983f-f1ea1b846433,d2ce2629-65b3-4b6d-a8d0-d139a240925d,dd147c7c-ca1e-4e77-b5b8-163fc4230770,da8fe672-cd66-4c74-b02b-61ed333f287b,f8d5f342-32a7-42c5-ba62-93fba54d1cc5,34b89767-7fe3-44d6-a379-fbe7d683b952,11dcf691-f32d-4faa-bd89-04e0a7fe55b4,4cfe8c85-1eea-4c22-9c07-44527eed8792,200c3d1a-2a49-4f4c-8aca-d28d3c7417fd,ddbdef74-c783-46b4-8d8d-eeeb9bacb319,6600a7db-4a95-42ba-9867-7f036398fb3c,4344ca82-efaa-4a37-b26e-cab267851708,e488b0dd-1ba9-41a1-bee2-7c3d0775936c,ad177280-f3d5-4e54-ae88-a8f34dc0dca7,ae66cfa2-df69-4bcd-b7cd-90dab7a386b8,518fad97-d0c4-4aef-b6aa-cda73739dde9,bfcdba53-0b90-4baa-bf77-6dcadc56905b,986474c1-3076-4a0b-addd-3dc1f8e5caad,9dd5597f-95fd-475a-9a21-8111874bb203,07da70cc-f6e6-4579-965f-0c3f636e0b5b,09166897-4a81-4ea3-a78f-a859e31afa1b,5f48a903-37f8-4c0c-b67a-7055258d53d6,0e796042-53ea-49d6-b5a9-9d86805bb611,71ee9a20-29f1-4e4b-8746-64de4024e713,ebbf718e-1ffc-44be-a498-28a564f772d7,0d04227b-d2ec-4052-8025-992150b6ac37,01df806f-756f-47a2-baf9-d1adc6ab245a,d3646dba-b1dc-4a84-b66d-5551416509c6,7982285f-b2bd-483e-8078-056bb3a1e43e,79a8acf9-9ec1-494d-bca2-21cb9834490c,1cf17836-1022-4535-85cd-084954b6dadc,b961f812-8c74-43ec-9093-07d9a37a1a90,a6f612f8-f9ef-4fcd-9326-26c5e71035eb,70ca7728-765a-4506-aa69-16cca1946e0b,ecac7bca-30e5-4372-ba88-df8dae4c7484,694f7c9a-ed46-4270-83c3-93ea46eee7a5,a90ae4cd-3e9b-42e1-bd0d-8e0fb62d085e,9fed464c-1067-4b49-984a-66b275085efd,bc8ecd72-1afc-4378-a4cb-b2610e46b266,dfd8fead-a1f1-4a8d-bb4b-6f07fb152455,9207a95a-6b45-4444-90ee-0ccd65d47535,a969192a-ff5c-41a9-b2bb-fde3024ef974,8d5143fc-1ff0-4b69-b58c-c7cc03d1f283,5a1aff0d-1127-4a25-a779-c4133b835d64,629e0e0f-99af-4bc8-99fa-6bac8bde9468,a505634c-35e1-4a45-ab50-ffb4da3f6dd3,2b9ca9fc-5057-46e9-b09a-833ea8cc5e9c,7379ecea-199a-421e-9e99-b70b9d54abce,d470a313-da5d-4ed3-bb9a-f26a43cb6971,f7e4f2d0-260d-42cd-a04e-6c126b42bbe9,702ee14e-6aa2-4a8a-9da8-8bb3c7fbab62,5ee44cf3-0ed2-483a-9a5f-c0be79f83a30,4532f813-efc1-4300-ae24-a63148c531ac,5122dc86-cbd8-48d7-89e2-c4247fc3d734,7020f0bb-a38b-4262-95e7-b0a6634e6e7f,70c3a6f2-2fd2-4db5-a89e-9a6a10b9e20c,6c877347-1c44-44d7-81b6-47b30f77a89d,2eb4f3c8-ac94-4929-9292-ac93bdaccb35,63aa4997-5f88-4c9c-a3ab-8118aaeaf9fc,ceed7eaa-c875-4431-84f4-ba94e21fe21f,eeb884f3-3cec-4272-9780-ae8a104830df,afc2d818-9fc5-44d5-92e0-493a1b5db721,b5e8b52d-02b1-4a50-8190-e414062e91a2,2efdef59-6dcd-4407-8c5f-2e5b404a3b4e,8ceacefe-533d-4ed5-ad58-4b1595e4e480,ca130eba-bb8c-4be9-a11e-9f6eb404a9d9,e486b041-484b-4585-b9ab-def01fdce0a5,61f372d4-66f6-43e6-8fe3-dce07af05855,916e7e0e-4ef8-4d61-b4a7-73d143ae59d2,6af367e0-87cb-4a78-8159-60e5be4876da,16831982-385f-4686-8fbc-af963913ee82,b92cb71b-e599-4180-8dce-2ad5da9285ce,095a70ed-fc06-4f85-80ab-789e4a4611d9,cabd3c0a-81a5-48dd-bbbb-0824d3fc6c7b,70708b03-10e0-47f3-bbf3-b8abaa1d86a1,f4147382-c8d1-47d4-b373-c47130ec6e00,52df20f5-29fc-4960-ab15-3fbca8c58118,f6a43327-d0f9-46f6-a3d3-ab81e7c97167,8174367c-3e53-4457-8f8c-c83169dd9bcc,8b429dec-b2c1-45d7-be31-166b5c6a29a8,83dca120-35a4-4083-83f4-b258dae63792,7d9868e4-69d1-4e8c-9f96-12a04a4271f1,71d19339-aecc-4d56-8c4b-8ce4f3924d00,7a7385ba-cb5f-4ccb-b959-b15beea27e90,00efc741-556b-48b0-be7c-7dbb11a0bb5b,9dd5f1ab-4b93-42e6-92ad-e9dd22d7c44f,4df9a580-e20c-49d1-ac57-b6d40a20ead9,17d6e157-83a3-4e24-b09a-f46e6dd425c8,20a8a82d-9727-4281-b8d6-8489e271cbae,c0781828-3635-4116-ba26-f51566ff54d8,db776b7b-0a8a-46a9-9ed3-2824591fc828,56e2cfe8-1579-41ec-900a-5721ee0eb192,acc3d13f-04ea-4f08-b72c-e099e1dbe538,7851d0e7-5576-4525-8095-7ff46c227fe8,c2751974-2ba1-4fae-92be-64ff5ed4e8cd,0024d3c4-9266-486e-bbf2-3d96fe6562f5,30581c1f-608b-4321-89b2-7acf0b44ae29,45ee5606-c1ab-4240-bada-e18148046d58,8a18fd61-7331-4819-bc2e-8900717b1df9,67194334-0c80-4d92-a568-ca037d43eb42,2cdb45e1-ddc8-409a-bc9c-3e2b0d5a810c,08f6e247-141f-459a-9a54-8e94e8032767,613b3d45-6272-4232-86e5-64d76fb3cdf7,c04608ec-2006-42fc-b548-22af5a9fe8dc,aadc7a8a-6716-4ffe-a006-79a5de2b5669,dd8bb3f1-d954-4f41-86d6-b771c2d10321,9e05ca5b-48c5-435f-b7eb-40d87b0524df,cfa68586-ddfe-45ce-902b-c649c3809ec1,059e4153-f0ce-4444-89bc-4447fd28f92a,cd45ed46-86a1-4931-a3d7-d05e19fb22a1,63aa6928-f2f3-4a41-bab3-5e174a01595a,b50ae83c-b7ad-4d9d-abf7-61403933f351,678c670e-5e88-48e7-b000-909921772358,d18fa15e-ae03-4f59-bc1b-fee6aac45883,3646f94c-4e24-4a2e-abb9-6497b38568de,dd8d3398-49fd-4856-9c72-51660e45ba3b,e0847bb5-bd76-4566-878a-cba9621db3a9,41b8a5f0-8530-44f2-b0ef-7343ca92c8ea,770a8d06-a014-492a-8937-ad4ae63d9490,d798e190-a355-4b94-96a4-4bf86aec8669,24b64d61-ffd9-474a-9d53-5ad8f3333e70,fefb7601-aaa0-4728-a8a3-447935a6190c,7e5f1b7c-5b7c-40ed-b8c8-f0331acc0ff0,1e59b667-0708-407e-8871-c18d268c82ee,852f3c69-5235-45b7-91fd-ef97407da78d,da3c1b6a-1f05-47b6-a9f6-e6a69233d406,4f948ee1-f4b7-4559-aadc-48cbfc3950c6,fde6fac2-5b50-43a2-b099-85fdb793ad12,5ab77e6b-3fa0-4e5f-b806-fa906df50e36,4d1efe6c-be84-432a-8d84-f716544fa947,18a77da9-7a88-4a69-9abb-977ff0f32ffc,3709febf-1be0-4404-b187-6f8e6e6d6764,1dba7651-d0cd-4a64-9cb2-b27600ffa9c8,d71d392d-eec9-4815-84b3-f518a0c1a6c9,b4afcf6b-adf8-481a-abf7-1e5392e0df19,052e97e3-4c15-4828-8f99-a84a779d15f8,41c3c353-30c0-4928-9c31-b4cc37275794,c2e5f25e-ae41-4eaa-b79f-1bfe634d7c2f,b9135bb1-918e-4205-9e0d-6c3b620e1787,322a8d1a-9daf-4e8b-99ae-00198e16f29d,5c434c1d-6201-41b0-a313-e8b0ca557b6c,99ead97a-bf6b-4cd0-830d-5b4d278b15ac,31a792b0-dc85-495a-a398-5bba3f73a31d,3ce7e52a-8204-480a-b790-3b7bf0793aaa,fb88968b-74e3-408a-b75d-8f28b3697192,61bc9b95-0db4-4f22-b5e0-c0100d352278,c20ba11d-6f2d-42c9-9b45-87153dfe6d69,71af10b2-1d3c-49e0-a022-49ab7e6cfc82,9067da0e-8dc4-4c4d-b95d-970d9cc23ee8,ed511565-caeb-47b0-bb7a-ebaa98a403d6,ab7d2a9b-12f0-482e-b077-4ed776e34fc3,b4a06cb2-0afe-4349-8fa1-e57b79c3619d,07c248ad-ca9b-48ae-ae4b-7899ce6bfbd3,ce62af69-2473-46e0-afa8-4ba5319069cd,ce0e6456-a14d-4605-b3b8-bcf2d2d28f11,bc3ce438-a5c0-4f8c-a9d0-5da160148011,a634dc29-52bc-4c8c-a9b8-247bd1d39d44,8558b3c0-4593-4149-8976-7bce5c292a3f,2a7e4bc2-42ca-4e84-aff7-a7db248662f8,51a9d8da-becc-4331-87e2-c9f1e675fb9c,cb6c7934-7cdc-4d8a-8467-612313209c68,165a3483-7a35-4f93-ad51-4ba3f47bc2f4,e6d0e9e0-874c-4732-81ad-36b7d2bafb83,b2ffdbc6-522c-46f5-a79e-433c8391cde1,598ca6b4-66f0-448c-b92b-fa62a3a2cc65,740c930f-5079-4fdc-92c6-6c8d7a46dc17,fbdafada-8a1c-4c97-891a-cf561c992159,07c4d482-a890-4a77-886e-a02a6aae7f9f,b3283ff9-799d-46bb-a4bd-9bd18ea9ce3f,b71bb05e-17e0-4fd6-838d-0510ce8c0cc1,205dcc0e-8aa0-4497-b263-e96aeafc87f1,8a2e5c97-4ef9-412e-a8ab-be50bf2fb8de,2464fcc0-64cb-4036-849e-fcb740085da8,c19fb793-745e-4594-8785-26a25464e2e1,f763e68d-5bc9-434f-8d96-f2c7e0379e95,73c91801-3d35-4604-805f-b3d29dc974dc

**Comment by PlasmaWave** [comment]
> The source code to allow easy install of the bookmarklet is here:
> https://github.com/rragan/rragan.github.io/blob/main/FoundLabsIdBookmarklet.html

@rragan I am not familiar with creating bookmarklets - I did create 'a' bookmarklet but it clearly is not referencing/running your code, only pulling webpage URLs I entered. I played around but can't figure how to install your code.

Would you mind explaining how and where to install the code? Many thnaks.

**Comment by jmarlman** [comment]
I HAVE THE SAME ISSUE OF COMPLETE  LAB CACHES  THAT ARE IN MY FOUND EXCLUDE SOURCE ARE  SHOWING UP IN THE OUTPUT.   THIS PROBLEM IS GETTING WORST.   WHEN AND IF EVER WILL THIS PROBLEM BE RESOLVED.

**Comment by keenonkites** [comment]
Shouting won't help. You do not have a paid support contract, or do you ?

If you are unhappy then either solve it on your own if you are willing and capable or accept the situation as it is.

Cheers

**Comment by mirsch** [comment]
new version using api v4 is online. no need for copy & paste anymore.
