### ISSUE TITLE
bekomme Projekt nicht zum laufen

### ISSUE THREAD

**Issue by widdi1977** [mirsch/lab2gpx#89]
Hallo Zusammen,
mir fehlen wohl noch Bestandteile.

Zuerst bekam ich den Fehler "exsistiert nicht" bei
require_once __DIR__ . '/vendor/autoload.php'; und require_once __DIR__ . '/config.local.php';
(einfach mal leer angelegt)

nun beschwert sich das PHP Script

Fatal error: Uncaught Error: Class 'Location\Factory\CoordinateFactory' not found in F:\XXXXX\lab2gpx\index.php:174 Stack trace: #0 {main} thrown in F:\XXXX\lab2gpx\index.php on line 174

Daher vermute ich, dass mir wohl noch folgender Bestandteil fehlt:

Zeile 23 ff
use App\Exporter\CacheturDotNoExporter;
use App\Exporter\GpxExporter;
use App\Exporter\GpxWaypointExporter;
use Location\Coordinate;
use Location\Factory\CoordinateFactory;

woher bekomme ich diese abhängigen Skripte?

Für "Coordinatefactory" fand ich immerhin das hier: https://github.com/IsaacLyh/CSE110-HW2-Q1(Java)

Danke für nen Tipp :-)

**Comment by mirsch** [comment]
Du benötigst [composer](https://getcomposer.org/), das ist praktisch der Standard Dependency Manager für PHP.
Damit kannst Du die benötigten Bibliotheken laden und auch der Autoloader wird generiert.
Also einfach composer installieren und dann im Projekt Ordner:
`composer install`
ausführen.

Was Du außerdem benötigst ist der **consumer_key**. Du musst in der config einen gültigen Key eintragen. Siehe `$config['CONSUMER_KEY']`
Den Key zu bekommen dürfte das wahre Problem sein.

**Comment by zzFrankzz** [comment]
Eins habe ich noch: Wenn ich bei meiner Installation das Zip erstellen lassen erhalte ich eine leere Webseite und Fehler ist:

 [php7:error] [pid 3347] [client xxx.xxx.xxx.xxx:64212] PHP Parse error:  syntax erro
r, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/lab2gpx/src/Expo
rter/AbstractExporter.php on line 7, referer: http://xxx.xxx.xxx.xxx/lab2gpx/

Habe keine Idee. Ich habe den Ordner 1:1 auf einen anderen Webserver gezogen. Dort geht alles. Dort ist PHP7.4.25 installiert
Auf dem Server wo der Fehler entsteht: 7.3.31
Any Ideas ?

**Comment by mirsch** [comment]
ja, das liegt an der PHP Version. Mindestens 7.4

**Comment by chris2286266** [comment]
Oder du nimmst in AbstractExporter.php in den Zeilen 7, 9 und 11 "protected" raus. Ist zwar nicht "schön" sollte aber wirken.

**Comment by zzFrankzz** [comment]
Anhand der Fehlermeldung war ich mir nicht sicher. Ich kann ja auf v7.4 upgraden. Danke Euch!

**Comment by djmajino** [comment]
Hello, so I managed to run this code, however I can't do anything with it, because I have missing X-Consumer-Key and I have no idea where or how to get it. I would appreciate any answer regarding this X-Consumer-Key item. Thanks a lot.

**Comment by mirsch** [comment]
> Hello, so I managed to run this code, however I can't do anything with it, because I have missing X-Consumer-Key and I have no idea where or how to get it. I would appreciate any answer regarding this X-Consumer-Key item. Thanks a lot.

I use the key from the original app. Monitored the network traffic between the device and the api.
