### ISSUE TITLE
Individual Lab Stages missing from gpx above certain number of WPs

### ISSUE THREAD

**Issue by PlasmaWave** [mirsch/lab2gpx#9]
Mirko ...

I noticed one stage of a local lab was missing from my gpx download, so carried out some checks and identified one stage was missing from three local Labs, i.e. all within 10km to 20km of the set co-ords.

Further tests with the browser tool, using various combinations of "Radius" and "Max Caches", identified the 'problem' began to show at around 1197 total waypoints (approx 230 Labs) where one of my test lab stages was not being imported. A second of my three test lab stages started to be missed from the gpx at around 3150 waypoints (approx 625 Labs). There may be other stages missing but I only checked against the three already identified.

Marking my completed labs as found, or not, was not a factor whether the three test stages were missed from the gpx.

Is it possible to check why certain stages are being missed by the tool? Very strange why just one stage from certain Labs is being missed and would ideally not happen - especially for local Labs.

I can send a spreadsheet with all the details if of help.

Many thanks ...
_____________________________________________________________________

Referring to my tests ... one stage of three separate Labs involved:

Lab Stage Ref: LC2A104 - included in gpx up to 1173 wps but missing at 1197 wps and above
Lab Stage Ref: LC163E6 - included in gpx up to 3026 wps but missing at 3150 wps and above
Lab Stage Ref: LC14B98 - missing from my original gpx but do not have any details. This stage was present in the gpx file for all tests carried out from 396 up to 5033 wps.
_____________________________________________________________________

Lab Stage URL: https://labs.geocaching.com/goto/NottinghamQMC
Lab Stage Name: Nottingham QMC : S1 QMC Main Entrance
Lab Stage Ref: LC2A104
Owner: Old Soldier

Lab Stage URL: https://labs.geocaching.com/goto/SideTracked-GCR
Lab Stage Name: REALLY SideTracked - Leicester London Road : S5 The London Road Bridge
Lab Stage Ref: LC163E6
Owner: stuarthowe11

Lab Stage URL: https://labs.geocaching.com/goto/HistoricMountsorrel	
Lab Stage Name: Historic Mountsorrel : S2 The Pinfold
Lab Stage Ref: LC14B98
Owner: longwhatton34

Centre Coordinates: 52.823786, -1.1874653	
X: Lab stage missing from gpx	
OK: Lab stage included in gpx

![Adv Labs Browser Tool Missing Stages](https://user-images.githubusercontent.com/72853430/104845593-30ca3e80-58ce-11eb-9c40-ec3a5ca010b7.jpg)

**Comment by mirsch** [comment]
Sorry, I can not reproduce this behavior.
Can you unzip a file which misses a station and open it in a text editor like notepad and search there for the station?

**Comment by PlasmaWave** [comment]
Interesting ... when the gpx files are viewed in Notepad my two "missing" stations are present, BUT there is a second stage/station with a duplicate code, which explains why only one of the two is loaded into the caching app or GSAK. Pure chance I noticed, but two of them were local Labs.

Further checks on the same gpx file showed a third duplicated code ... summary of the three duplicates given below and the full gpx file attached, if of help.

[labs2gpx 500kmx625.zip](https://github.com/mirsch/lab2gpx/files/5834006/labs2gpx.500kmx625.zip)

Labs Browser Tool Settings: 500km + 625 max caches centred on 52.823786, -1.1874653:
____________________________________________________________________________________________________________
</wpt><wpt lat="52.944766666667" lon="-1.1872666666667">
<name>LC2A104</name>
<desc>QMC Main Entrance</desc>
__________________________
</wpt><wpt lat="53.423333333333" lon="-2.18525">
<name>LC2A104</name>
<desc>Cecil Kimber</desc>
____________________________________________________________________________________________________________
</wpt><wpt lat="52.630383333333" lon="-1.1249">
<name>LC163E6</name>
<desc>The London Road Bridge</desc>
__________________________
</wpt><wpt lat="51.401333333333" lon="-1.3240166666667">
<name>LC163E6</name>
<desc>TOWN HALL</desc>
____________________________________________________________________________________________________________
</wpt><wpt lat="53.725716666667" lon="-1.7960333333333">
<name>LC7E957</name>
<desc>Sir Titus Salt</desc>
__________________________
</wpt><wpt lat="53.80115" lon="-1.5483333333333">
<name>LC7E957</name>
<desc>Nelson Mandela Gardens &amp; Millennium Square </desc>
____________________________________________________________________________________________________________

**Comment by mirsch** [comment]
Thank you very much for your research and detailed feedback.
because there is no code for the labs, the code was an abbreviated checksum over the UUID. 
I was hoping this would be unique enough, but...
So, I adjusted the code now and use an other unique identifier. Unfortunately every cache got a new code.

**Comment by PlasmaWave** [comment]
Many thanks for your fast solution ... looks good
