### ISSUE TITLE
Version auf Github vs. Webseite

### ISSUE THREAD

**Issue by GCHarald** [mirsch/lab2gpx#90]
Hi,
die Version auf Github ist ziemlich alt und ist auf jeden Fall eine andere als die der Webseite. Sind bei der Version auf der Webseite nur die Tagebucheinträge entfernt oder enthält sie weitere Updates?
Und wird die Version der Webseite auf Github hochgeladen?.

Danke und Gruß

Hi,
the version on Github is quite old and is definitely different from the one on the website. Is the version on the website just the diary entries removed or does it contain more updates?
And is the version on the website uploaded to Github?

Thanks and greetings

**Comment by mirsch** [comment]
Webseite entspricht (jetzt wieder) dem master branch. Gefehlt haben nur die entfernten Tagebucheinträge
Releases habe ich entfernt, da die nicht aktuell gehalten wurden. 
Changes lassen sich in den Commit messages ablesen
