### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by theyoungstone** [mirsch/lab2gpx#95]
Is there somewhere an installation guide, with requirements, to install a lab2gpx on another server?
Regards,

**Comment by chris2286266** [comment]
git clone ...
composer install
configure the "key"

that's it ;-)

**Comment by theyoungstone** [comment]
> 

git clone ...
--> done
composer install
--> done
configure the "key"
--> I don't know what to do. I have no config.local.php file into lab2gpx directory and I don't find any template.

**Comment by mirsch** [comment]
create a file called `config.local.php` the same directory as `index.php`
content of this file should be 
```php
<?php
$config['CONSUMER_KEY'] = 'THE-TOP-SECRET-CONSUMER-KEY';
```
replace `THE-TOP-SECRET-CONSUMER-KEY` with a valid consumer key

**Comment by theyoungstone** [comment]
Thank you
So I have to find a consumer key. I don't know how it works. I will search on geocaching.com
Thank you again
Regards,
