### ISSUE TITLE
Lab step answers owner message no longer being downloaded

### ISSUE THREAD

**Issue by Skinoku** [mirsch/lab2gpx#97]
Dear mirsch,
I recently used again your service and it appears it no longer downloads the "owner comments" that are shown on the Adventure Lap app once entering the correct answer.
If I'm not wrong, I remember that a flag was available in the webpage of your project allowing you to enable or disable such feature.
It was labelled something like "may contain spoilers" or something.
Was it an intentional removal or is there an issue?
Thank you for your work and best regards
Skinoku

![this is what I mean](https://user-images.githubusercontent.com/41749705/183965772-5d3a896b-7e1d-41b4-b6e6-f643b5df2907.jpg)

**Comment by GithubMarcel** [comment]
https://github.com/mirsch/lab2gpx/issues/88

**Comment by mirsch** [comment]
see #88
