### ISSUE TITLE
Undefined array key "Items" in ... 

### ISSUE THREAD

**Issue by Snoopie-dog** [mirsch/lab2gpx#98]
Hello Mirsch,

I'm trying to install the github version on my website for private use and testing.
When starting the program i'm receiving the rigth internet page with questions.

After selecting my choices i'm virtual pushing the Download button.

Then I'm receiving the error message on a new page:
Warning: Undefined array key "Items" in /home/deb66342/domains/nijboer.eu/public_html/lab2gpx/index.php on line 91

research gives the part of the statement: $labCaches['Items'] > 0

Is that because there is no rigth consumer key or is that another issue perhaps wrong installation? 
What's yout opinion?

**Comment by mirsch** [comment]
line 91 makes no sense to me. Did you modify `index.php`?
But because of the undefined array key I guess you don't have the right consumer key.
Try to output the result of the API call after line 77 
`$labCachesJson = fetch($url);`
add
`echo $labCachesJson; exit;`
let's see if this brings any info about the problem.

**Comment by Snoopie-dog** [comment]
Thanks for the reply.

 

I thought the name of the file was in the subject field.

But I deleted by shortening the subject .

 

Yes it was in the index.php-file.

 

After placing the statement I’ve got the message:

{"Message":"Authorization has been denied for this request."}

 

It seems to me it’s a problem caused by the missing consumer key.

 

The logfile (lab2gpx.log) on the server shows:

2022-08-16 13:18:37       2001:1c06:18c1:7700:6151:ec64:741d:57e5        {"coordinates":"52.26054, 6.80488","radius":25,"take":300,"cacheType":"Lab Cache","prefix":"LC",

"codeIsCaseSensitive":"0","linear":"default","includeQuestion":"on","includeWaypointDescription":"on","includeCacheDescription":"on",

"includeAwardMessage":false,"excludeOwner":"","includeFinds":"0","uuidsToExclude":[],"outputFormat":"gpx","downloadButton":"Download"}

 

 

 

 

Van: mirsch ***@***.***> 
Verzonden: Tuesday, 16 August 2022 13:03
Aan: mirsch/lab2gpx ***@***.***>
CC: Snoopie-dog ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mirsch/lab2gpx] Undefined array key "Items" in ... (Issue #98)

 

line 91 makes no sense to me. Did you modify index.php?
But because of the undefined array key I guess you don't have the right consumer key.
Try to output the result of the API call after line 77
$labCachesJson = fetch($url);
add
echo $labCachesJson; exit;
let's see if this brings any info about the problem.

**Comment by mirsch** [comment]
so you have to do some research to get a valid consumer key ;)
